-- #####################################################################
--  3.1.4.1_audit_log.sql
--  3.1.4.1  The audit log
-- #####################################################################
--  GENERATED from queries/Tests.sql (section 12) by
--  tests/split_sql_tests.sh - edit Tests.sql and run the script again,
--  do not edit this file by hand.
--
--  It runs on its own: it installs the small test harness, runs the
--  checks of this one question inside a transaction, rolls everything
--  back and prints a PASS/FAIL report. It changes nothing.
--  (The client warns about a non-transactional table at the end: that
--  is the MEMORY table that carries the report through the rollback.)
--
--  Run it with
--    docker exec -i baseis-mariadb mariadb -uroot -pjohn2005 -t baseisproject < queries/tests/3.1.4.1_audit_log.sql
--  or open it in a SQL client and execute the whole file.
-- #####################################################################

-- #####################################################################
--  THE TEST HARNESS
--  Six helper procedures record one line per check instead of stopping at
--  the first failure, so one run reports everything at once.
--  They are dropped again at the end of the file.
-- #####################################################################

DROP TEMPORARY TABLE IF EXISTS test_results;
CREATE TEMPORARY TABLE test_results (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    section  VARCHAR(60),
    test     VARCHAR(200),
    status   VARCHAR(4),
    expected VARCHAR(255),
    actual   VARCHAR(255)
) ENGINE = MEMORY;   -- MEMORY is not transactional: the report survives the ROLLBACK

DELIMITER $$

-- write one line of the report
DROP PROCEDURE IF EXISTS t_record$$
CREATE PROCEDURE t_record(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                          IN p_status VARCHAR(4), IN p_expected VARCHAR(255), IN p_actual VARCHAR(255))
BEGIN
    INSERT INTO test_results (section, test, status, expected, actual)
    VALUES (p_section, p_test, p_status, LEFT(p_expected, 255), LEFT(p_actual, 255));
END$$

-- the value must be exactly the expected one
DROP PROCEDURE IF EXISTS t_eq$$
CREATE PROCEDURE t_eq(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                      IN p_actual TEXT, IN p_expected TEXT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual <=> p_expected, 'PASS', 'FAIL'),
                  IFNULL(p_expected, 'NULL'), IFNULL(p_actual, 'NULL'));
END$$

-- the value must be at least the expected minimum (the row counts of 3.1.1)
DROP PROCEDURE IF EXISTS t_min$$
CREATE PROCEDURE t_min(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual BIGINT, IN p_min BIGINT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual >= p_min, 'PASS', 'FAIL'),
                  CONCAT('>= ', p_min), CAST(p_actual AS CHAR));
END$$

-- the value must contain the expected text
DROP PROCEDURE IF EXISTS t_has$$
CREATE PROCEDURE t_has(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual TEXT, IN p_expected VARCHAR(255))
BEGIN
    CALL t_record(p_section, p_test,
                  IF(INSTR(IFNULL(p_actual, ''), p_expected) > 0, 'PASS', 'FAIL'),
                  CONCAT('contains "', p_expected, '"'), IFNULL(p_actual, 'NULL'));
END$$

-- THE REFUSED PATH: the statement must fail, with a message we expect.
-- The handler catches the SIGNAL raised by a trigger or a procedure, so the
-- suite can carry on and report it as a passing test.
DROP PROCEDURE IF EXISTS t_error$$
CREATE PROCEDURE t_error(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                         IN p_sql TEXT, IN p_expected VARCHAR(255))
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    IF v_msg = '' THEN
        CALL t_record(p_section, p_test, 'FAIL',
                      CONCAT('refused: "', p_expected, '"'), 'the statement was ACCEPTED');
    ELSE
        CALL t_record(p_section, p_test, IF(INSTR(v_msg, p_expected) > 0, 'PASS', 'FAIL'),
                      CONCAT('refused: "', p_expected, '"'), v_msg);
    END IF;
END$$

-- THE ACCEPTED PATH: the statement must go through without an error
DROP PROCEDURE IF EXISTS t_ok$$
CREATE PROCEDURE t_ok(IN p_section VARCHAR(60), IN p_test VARCHAR(200), IN p_sql TEXT)
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    CALL t_record(p_section, p_test, IF(v_msg = '', 'PASS', 'FAIL'), 'accepted',
                  IF(v_msg = '', 'accepted', v_msg));
END$$

DELIMITER ;


-- #####################################################################
--  Everything from here is undone by the ROLLBACK below
-- #####################################################################
START TRANSACTION;

-- =====================================================================
--  SECTION 12 - 3.1.4.1  The audit log
-- ---------------------------------------------------------------------
--  21 triggers: INSERT, UPDATE and DELETE on each of the seven tables
--  trip, reservation, customer, destination, vehicle, lodging, room_usage.
--  Each one writes a row into log_actions with the account, the time, the
--  table, the kind of action and a readable description.
--  log_actions.log_dba_username is a foreign key to dba_users, so an
--  account that is not a registered DBA cannot change the data at all.
--  Outcomes: every table logs all three actions (tested one by one), and
--  the refused path where the account is not registered (tested last,
--  because it empties the log).
-- =====================================================================
SET @log_before = (SELECT COUNT(*) FROM log_actions);

INSERT INTO customer (cust_name, cust_lname, cust_birth_date) VALUES ('Log', 'Test', '1990-01-01');
UPDATE customer SET cust_phone = '123' WHERE cust_lname = 'Test';
DELETE FROM customer WHERE cust_lname = 'Test';

INSERT INTO destination (dst_name, dst_rtype, dst_language_code) VALUES ('Logville', 'LOCAL', 'EN');
UPDATE destination SET dst_descr = 'x' WHERE dst_name = 'Logville';
DELETE FROM destination WHERE dst_name = 'Logville';

INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
VALUES (1, 'LOG-0001', 'M', 'B', 'Car', 4);
UPDATE vehicle SET v_status = 'Maintenance' WHERE v_license_plate = 'LOG-0001';
DELETE FROM vehicle WHERE v_license_plate = 'LOG-0001';

INSERT INTO lodging (lg_dst_id, lg_name, lg_type, lg_address, lg_city, lg_total_rooms, lg_cost_per_night)
VALUES (1, 'Log Lodge', 'Hotel', 'a', 'Paris', 5, 10);
UPDATE lodging SET lg_cost_per_night = 11 WHERE lg_name = 'Log Lodge';
DELETE FROM lodging WHERE lg_name = 'Log Lodge';

INSERT INTO room_usage (ru_trip_id, ru_lodging_id, ru_checkin, ru_checkout, ru_rooms_count)
VALUES (11, 1, '2026-10-02', '2026-10-04', 1);
UPDATE room_usage SET ru_rooms_count = 2 WHERE ru_trip_id = 11;
DELETE FROM room_usage WHERE ru_trip_id = 11;

INSERT INTO reservation (res_tr_id, res_seatnum, res_cust_id, res_status) VALUES (5, 9, 1, 'PENDING');
UPDATE reservation SET res_status = 'CONFIRMED' WHERE res_tr_id = 5 AND res_seatnum = 9;
DELETE FROM reservation WHERE res_tr_id = 5 AND res_seatnum = 9;

INSERT INTO trip (tr_departure, tr_return, tr_maxseats, tr_cost_adult, tr_cost_child, tr_status, tr_br_code)
VALUES ('2027-03-01', '2027-03-05', 10, 100, 50, 'PLANNED', 1);
UPDATE trip SET tr_status = 'CANCELLED' WHERE tr_departure = '2027-03-01';
DELETE FROM trip WHERE tr_departure = '2027-03-01';

CALL t_eq('12. 3.1.4.1 audit log', '7 tables x 3 actions produce exactly 21 log rows',
    (SELECT COUNT(*) - @log_before FROM log_actions), '21');

-- one check per table: all three actions have to be there.
-- log_action_type is an ENUM, so it sorts in the order it was declared.
CALL t_eq('12. 3.1.4.1 audit log', 'customer logs INSERT, UPDATE and DELETE',
    (SELECT GROUP_CONCAT(DISTINCT log_action_type ORDER BY log_action_type) FROM log_actions
     WHERE log_table_name = 'customer' AND log_id > @log_before), 'INSERT,UPDATE,DELETE');
CALL t_eq('12. 3.1.4.1 audit log', 'destination logs INSERT, UPDATE and DELETE',
    (SELECT GROUP_CONCAT(DISTINCT log_action_type ORDER BY log_action_type) FROM log_actions
     WHERE log_table_name = 'destination' AND log_id > @log_before), 'INSERT,UPDATE,DELETE');
CALL t_eq('12. 3.1.4.1 audit log', 'vehicle logs INSERT, UPDATE and DELETE',
    (SELECT GROUP_CONCAT(DISTINCT log_action_type ORDER BY log_action_type) FROM log_actions
     WHERE log_table_name = 'vehicle' AND log_id > @log_before), 'INSERT,UPDATE,DELETE');
CALL t_eq('12. 3.1.4.1 audit log', 'lodging logs INSERT, UPDATE and DELETE',
    (SELECT GROUP_CONCAT(DISTINCT log_action_type ORDER BY log_action_type) FROM log_actions
     WHERE log_table_name = 'lodging' AND log_id > @log_before), 'INSERT,UPDATE,DELETE');
CALL t_eq('12. 3.1.4.1 audit log', 'room_usage logs INSERT, UPDATE and DELETE',
    (SELECT GROUP_CONCAT(DISTINCT log_action_type ORDER BY log_action_type) FROM log_actions
     WHERE log_table_name = 'room_usage' AND log_id > @log_before), 'INSERT,UPDATE,DELETE');
CALL t_eq('12. 3.1.4.1 audit log', 'reservation logs INSERT, UPDATE and DELETE',
    (SELECT GROUP_CONCAT(DISTINCT log_action_type ORDER BY log_action_type) FROM log_actions
     WHERE log_table_name = 'reservation' AND log_id > @log_before), 'INSERT,UPDATE,DELETE');
CALL t_eq('12. 3.1.4.1 audit log', 'trip logs INSERT, UPDATE and DELETE',
    (SELECT GROUP_CONCAT(DISTINCT log_action_type ORDER BY log_action_type) FROM log_actions
     WHERE log_table_name = 'trip' AND log_id > @log_before), 'INSERT,UPDATE,DELETE');

CALL t_eq('12. 3.1.4.1 audit log', 'all seven tables of the requirement are covered',
    (SELECT COUNT(DISTINCT log_table_name) FROM log_actions WHERE log_id > @log_before), '7');
CALL t_eq('12. 3.1.4.1 audit log', 'the account that made the change is recorded',
    (SELECT COUNT(DISTINCT log_dba_username) FROM log_actions WHERE log_id > @log_before), '1');
CALL t_eq('12. 3.1.4.1 audit log', 'the account is stored without the host name',
    (SELECT DISTINCT log_dba_username FROM log_actions WHERE log_id > @log_before),
    (SELECT SUBSTRING_INDEX(USER(), '@', 1)));
CALL t_eq('12. 3.1.4.1 audit log', 'every log row carries the time of the change',
    (SELECT COUNT(*) FROM log_actions WHERE log_timestamp IS NULL), '0');
CALL t_has('12. 3.1.4.1 audit log', 'the log says what changed, not only that something did',
    (SELECT log_details FROM log_actions
     WHERE log_table_name = 'vehicle' AND log_action_type = 'UPDATE' AND log_id > @log_before
     ORDER BY log_id DESC LIMIT 1), 'Available -> Maintenance');

-- the refused path: an account that is not a registered DBA may change nothing.
-- (The log has to be emptied first, because log_actions references dba_users.)
DELETE FROM log_actions;
DELETE FROM dba_users WHERE dba_username = SUBSTRING_INDEX(USER(), '@', 1);
CALL t_error('12. 3.1.4.1 audit log', 'an account that is not a registered DBA cannot change data',
    "INSERT INTO customer (cust_name, cust_lname) VALUES ('Not', 'ADba')",
    'foreign key constraint fails');
INSERT INTO dba_users (dba_username, dba_start_date) VALUES (SUBSTRING_INDEX(USER(), '@', 1), CURDATE());
CALL t_ok('12. 3.1.4.1 audit log', 'once the account is registered again the change goes through',
    "INSERT INTO customer (cust_name, cust_lname) VALUES ('Now', 'ADba')");
DELETE FROM customer WHERE cust_lname = 'ADba';


-- #####################################################################
--  Undo everything the checks did
-- #####################################################################
ROLLBACK;


-- #####################################################################
--  THE REPORT
-- #####################################################################

-- 1. every check, in order
SELECT id, section, test, status FROM test_results ORDER BY id;

-- 2. the failures on their own, with what was expected and what came back
SELECT id, section, test, expected, actual
FROM test_results WHERE status = 'FAIL' ORDER BY id;

-- 3. the summary
SELECT COUNT(*)             AS total,
       SUM(status = 'PASS') AS passed,
       SUM(status = 'FAIL') AS failed,
       IF(SUM(status = 'FAIL') = 0, 'ALL TESTS PASSED', 'THERE ARE FAILURES') AS result
FROM test_results;

-- 4. the proof that the database was left exactly as it was found
SELECT 'the tests changed nothing' AS note,
       (SELECT COUNT(*) FROM customer)    AS customers,
       (SELECT COUNT(*) FROM reservation) AS reservations,
       (SELECT COUNT(*) FROM room_usage)  AS room_usage_rows,
       (SELECT COUNT(*) FROM log_actions) AS log_rows,
       (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9) AS vehicle_9,
       (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101')                AS salary_AT101;


-- #####################################################################
--  Remove the harness again
-- #####################################################################
DROP PROCEDURE IF EXISTS t_record;
DROP PROCEDURE IF EXISTS t_eq;
DROP PROCEDURE IF EXISTS t_min;
DROP PROCEDURE IF EXISTS t_has;
DROP PROCEDURE IF EXISTS t_error;
DROP PROCEDURE IF EXISTS t_ok;
DROP TEMPORARY TABLE IF EXISTS test_results;
