-- #####################################################################
--  3.1.3.2_search_accommodation.sql
--  3.1.3.2  Searching for accommodation
-- #####################################################################
--  GENERATED from queries/Tests.sql (section 8) by
--  tests/split_sql_tests.sh - edit Tests.sql and run the script again,
--  do not edit this file by hand.
--
--  It runs on its own: it installs the small test harness, runs the
--  checks of this one question inside a transaction, rolls everything
--  back and prints a PASS/FAIL report. It changes nothing.
--  (The client warns about a non-transactional table at the end: that
--  is the MEMORY table that carries the report through the rollback.)
--
--  Run it with
--    docker exec -i baseis-mariadb mariadb -uroot -pjohn2005 -t baseisproject < queries/tests/3.1.3.2_search_accommodation.sql
--  or open it in a SQL client and execute the whole file.
-- #####################################################################

-- #####################################################################
--  THE TEST HARNESS
--  Six helper procedures record one line per check instead of stopping at
--  the first failure, so one run reports everything at once.
--  They are dropped again at the end of the file.
-- #####################################################################

DROP TEMPORARY TABLE IF EXISTS test_results;
CREATE TEMPORARY TABLE test_results (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    section  VARCHAR(60),
    test     VARCHAR(200),
    status   VARCHAR(4),
    expected VARCHAR(255),
    actual   VARCHAR(255)
) ENGINE = MEMORY;   -- MEMORY is not transactional: the report survives the ROLLBACK

DELIMITER $$

-- write one line of the report
DROP PROCEDURE IF EXISTS t_record$$
CREATE PROCEDURE t_record(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                          IN p_status VARCHAR(4), IN p_expected VARCHAR(255), IN p_actual VARCHAR(255))
BEGIN
    INSERT INTO test_results (section, test, status, expected, actual)
    VALUES (p_section, p_test, p_status, LEFT(p_expected, 255), LEFT(p_actual, 255));
END$$

-- the value must be exactly the expected one
DROP PROCEDURE IF EXISTS t_eq$$
CREATE PROCEDURE t_eq(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                      IN p_actual TEXT, IN p_expected TEXT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual <=> p_expected, 'PASS', 'FAIL'),
                  IFNULL(p_expected, 'NULL'), IFNULL(p_actual, 'NULL'));
END$$

-- the value must be at least the expected minimum (the row counts of 3.1.1)
DROP PROCEDURE IF EXISTS t_min$$
CREATE PROCEDURE t_min(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual BIGINT, IN p_min BIGINT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual >= p_min, 'PASS', 'FAIL'),
                  CONCAT('>= ', p_min), CAST(p_actual AS CHAR));
END$$

-- the value must contain the expected text
DROP PROCEDURE IF EXISTS t_has$$
CREATE PROCEDURE t_has(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual TEXT, IN p_expected VARCHAR(255))
BEGIN
    CALL t_record(p_section, p_test,
                  IF(INSTR(IFNULL(p_actual, ''), p_expected) > 0, 'PASS', 'FAIL'),
                  CONCAT('contains "', p_expected, '"'), IFNULL(p_actual, 'NULL'));
END$$

-- THE REFUSED PATH: the statement must fail, with a message we expect.
-- The handler catches the SIGNAL raised by a trigger or a procedure, so the
-- suite can carry on and report it as a passing test.
DROP PROCEDURE IF EXISTS t_error$$
CREATE PROCEDURE t_error(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                         IN p_sql TEXT, IN p_expected VARCHAR(255))
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    IF v_msg = '' THEN
        CALL t_record(p_section, p_test, 'FAIL',
                      CONCAT('refused: "', p_expected, '"'), 'the statement was ACCEPTED');
    ELSE
        CALL t_record(p_section, p_test, IF(INSTR(v_msg, p_expected) > 0, 'PASS', 'FAIL'),
                      CONCAT('refused: "', p_expected, '"'), v_msg);
    END IF;
END$$

-- THE ACCEPTED PATH: the statement must go through without an error
DROP PROCEDURE IF EXISTS t_ok$$
CREATE PROCEDURE t_ok(IN p_section VARCHAR(60), IN p_test VARCHAR(200), IN p_sql TEXT)
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    CALL t_record(p_section, p_test, IF(v_msg = '', 'PASS', 'FAIL'), 'accepted',
                  IF(v_msg = '', 'accepted', v_msg));
END$$

DELIMITER ;


-- #####################################################################
--  Everything from here is undone by the ROLLBACK below
-- #####################################################################
START TRANSACTION;

-- =====================================================================
--  SECTION 8 - 3.1.3.2  Searching for accommodation
-- ---------------------------------------------------------------------
--  Procedure: sp_search_accommodation(destination, arrival, departure,
--                                     rooms, OUT first_lodging_id)
--  It lists the lodgings of a destination that still have enough free
--  rooms in that period, cheapest first (then more stars, then a better
--  rating), and returns the id of the best one in the OUT parameter.
--  Rooms already booked in room_usage for an overlapping period are
--  subtracted from the free rooms.
--  Outcomes: a match is found / nothing is found because there are not
--  enough rooms, because the lodging is inactive, or because the
--  destination has none at all. All are tested, plus the ordering.
--  Destination 1 is Paris; lodging 1 is Le Grand Paris, 100 rooms, 250/night.
-- =====================================================================
CALL sp_search_accommodation(1, '2026-06-01', '2026-06-05', 2, @lodging_id);
CALL t_eq('8. 3.1.3.2 search', 'FOUND: the hotel of Paris is returned in the OUT parameter',
    (SELECT lg_name FROM lodging WHERE lg_id = @lodging_id), 'Le Grand Paris');

-- 95 of the 100 rooms are taken for a period that overlaps the search
INSERT INTO room_usage (ru_trip_id, ru_lodging_id, ru_checkin, ru_checkout, ru_rooms_count)
VALUES (11, 1, '2026-06-03', '2026-06-07', 95);
CALL sp_search_accommodation(1, '2026-06-01', '2026-06-05', 5, @lodging_id);
CALL t_eq('8. 3.1.3.2 search', 'existing bookings reduce the free rooms: 5 are still free',
    CAST(@lodging_id AS CHAR), '1');
CALL sp_search_accommodation(1, '2026-06-01', '2026-06-05', 6, @lodging_id);
CALL t_eq('8. 3.1.3.2 search', 'NOT FOUND: asking for 6 of the 5 free rooms returns NULL',
    IFNULL(CAST(@lodging_id AS CHAR), 'NULL'), 'NULL');
CALL sp_search_accommodation(1, '2026-06-07', '2026-06-09', 6, @lodging_id);
CALL t_eq('8. 3.1.3.2 search', 'a period that does not overlap the booking is unaffected',
    CAST(@lodging_id AS CHAR), '1');
DELETE FROM room_usage WHERE ru_trip_id = 11;

-- an inactive lodging is not offered at all
UPDATE lodging SET lg_status = 'Inactive' WHERE lg_id = 1;
CALL sp_search_accommodation(1, '2026-09-01', '2026-09-03', 1, @lodging_id);
CALL t_eq('8. 3.1.3.2 search', 'NOT FOUND: a lodging that is Inactive is never offered',
    IFNULL(CAST(@lodging_id AS CHAR), 'NULL'), 'NULL');
UPDATE lodging SET lg_status = 'Active' WHERE lg_id = 1;

-- a destination with no lodging at all
INSERT INTO destination (dst_name, dst_rtype, dst_language_code) VALUES ('Nowhere', 'LOCAL', 'EN');
SET @nowhere = LAST_INSERT_ID();
CALL sp_search_accommodation(@nowhere, '2026-09-01', '2026-09-03', 1, @lodging_id);
CALL t_eq('8. 3.1.3.2 search', 'NOT FOUND: a destination without any lodging returns NULL',
    IFNULL(CAST(@lodging_id AS CHAR), 'NULL'), 'NULL');
DELETE FROM destination WHERE dst_id = @nowhere;

-- the order is: cheapest first, then more stars, then a better rating.
-- Two lodgings at the same price - the one with stars must win.
INSERT INTO lodging (lg_dst_id, lg_name, lg_type, lg_stars, lg_rating, lg_address, lg_city, lg_total_rooms, lg_cost_per_night)
VALUES (1, 'Sort Budget Inn', 'Hostel', NULL, 3.0, 'Rue X', 'Paris', 20, 30.00),
       (1, 'Sort Mid Hotel',  'Hotel',  3,    4.0, 'Rue Y', 'Paris', 20, 30.00);
CALL sp_search_accommodation(1, '2026-09-01', '2026-09-03', 1, @lodging_id);
CALL t_eq('8. 3.1.3.2 search', 'the cheapest is offered first (30.00 beats 250.00)',
    (SELECT lg_cost_per_night FROM lodging WHERE lg_id = @lodging_id), '30.00');
CALL t_eq('8. 3.1.3.2 search', 'at the same price the one with stars comes first',
    (SELECT lg_name FROM lodging WHERE lg_id = @lodging_id), 'Sort Mid Hotel');
DELETE FROM lodging WHERE lg_name LIKE 'Sort %';


-- #####################################################################
--  Undo everything the checks did
-- #####################################################################
ROLLBACK;


-- #####################################################################
--  THE REPORT
-- #####################################################################

-- 1. every check, in order
SELECT id, section, test, status FROM test_results ORDER BY id;

-- 2. the failures on their own, with what was expected and what came back
SELECT id, section, test, expected, actual
FROM test_results WHERE status = 'FAIL' ORDER BY id;

-- 3. the summary
SELECT COUNT(*)             AS total,
       SUM(status = 'PASS') AS passed,
       SUM(status = 'FAIL') AS failed,
       IF(SUM(status = 'FAIL') = 0, 'ALL TESTS PASSED', 'THERE ARE FAILURES') AS result
FROM test_results;

-- 4. the proof that the database was left exactly as it was found
SELECT 'the tests changed nothing' AS note,
       (SELECT COUNT(*) FROM customer)    AS customers,
       (SELECT COUNT(*) FROM reservation) AS reservations,
       (SELECT COUNT(*) FROM room_usage)  AS room_usage_rows,
       (SELECT COUNT(*) FROM log_actions) AS log_rows,
       (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9) AS vehicle_9,
       (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101')                AS salary_AT101;


-- #####################################################################
--  Remove the harness again
-- #####################################################################
DROP PROCEDURE IF EXISTS t_record;
DROP PROCEDURE IF EXISTS t_eq;
DROP PROCEDURE IF EXISTS t_min;
DROP PROCEDURE IF EXISTS t_has;
DROP PROCEDURE IF EXISTS t_error;
DROP PROCEDURE IF EXISTS t_ok;
DROP TEMPORARY TABLE IF EXISTS test_results;
