-- #####################################################################
--  3.1.3.1_assign_vehicle.sql
--  3.1.3.1  Assigning a vehicle to a trip
-- #####################################################################
--  GENERATED from queries/Tests.sql (section 10) by
--  tests/split_sql_tests.sh - edit Tests.sql and run the script again,
--  do not edit this file by hand.
--
--  It runs on its own: it installs the small test harness, runs the
--  checks of this one question inside a transaction, rolls everything
--  back and prints a PASS/FAIL report. It changes nothing.
--  (The client warns about a non-transactional table at the end: that
--  is the MEMORY table that carries the report through the rollback.)
--
--  Run it with
--    docker exec -i baseis-mariadb mariadb -uroot -pjohn2005 -t baseisproject < queries/tests/3.1.3.1_assign_vehicle.sql
--  or open it in a SQL client and execute the whole file.
-- #####################################################################

-- #####################################################################
--  THE TEST HARNESS
--  Six helper procedures record one line per check instead of stopping at
--  the first failure, so one run reports everything at once.
--  They are dropped again at the end of the file.
-- #####################################################################

DROP TEMPORARY TABLE IF EXISTS test_results;
CREATE TEMPORARY TABLE test_results (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    section  VARCHAR(60),
    test     VARCHAR(200),
    status   VARCHAR(4),
    expected VARCHAR(255),
    actual   VARCHAR(255)
) ENGINE = MEMORY;   -- MEMORY is not transactional: the report survives the ROLLBACK

DELIMITER $$

-- write one line of the report
DROP PROCEDURE IF EXISTS t_record$$
CREATE PROCEDURE t_record(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                          IN p_status VARCHAR(4), IN p_expected VARCHAR(255), IN p_actual VARCHAR(255))
BEGIN
    INSERT INTO test_results (section, test, status, expected, actual)
    VALUES (p_section, p_test, p_status, LEFT(p_expected, 255), LEFT(p_actual, 255));
END$$

-- the value must be exactly the expected one
DROP PROCEDURE IF EXISTS t_eq$$
CREATE PROCEDURE t_eq(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                      IN p_actual TEXT, IN p_expected TEXT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual <=> p_expected, 'PASS', 'FAIL'),
                  IFNULL(p_expected, 'NULL'), IFNULL(p_actual, 'NULL'));
END$$

-- the value must be at least the expected minimum (the row counts of 3.1.1)
DROP PROCEDURE IF EXISTS t_min$$
CREATE PROCEDURE t_min(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual BIGINT, IN p_min BIGINT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual >= p_min, 'PASS', 'FAIL'),
                  CONCAT('>= ', p_min), CAST(p_actual AS CHAR));
END$$

-- the value must contain the expected text
DROP PROCEDURE IF EXISTS t_has$$
CREATE PROCEDURE t_has(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual TEXT, IN p_expected VARCHAR(255))
BEGIN
    CALL t_record(p_section, p_test,
                  IF(INSTR(IFNULL(p_actual, ''), p_expected) > 0, 'PASS', 'FAIL'),
                  CONCAT('contains "', p_expected, '"'), IFNULL(p_actual, 'NULL'));
END$$

-- THE REFUSED PATH: the statement must fail, with a message we expect.
-- The handler catches the SIGNAL raised by a trigger or a procedure, so the
-- suite can carry on and report it as a passing test.
DROP PROCEDURE IF EXISTS t_error$$
CREATE PROCEDURE t_error(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                         IN p_sql TEXT, IN p_expected VARCHAR(255))
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    IF v_msg = '' THEN
        CALL t_record(p_section, p_test, 'FAIL',
                      CONCAT('refused: "', p_expected, '"'), 'the statement was ACCEPTED');
    ELSE
        CALL t_record(p_section, p_test, IF(INSTR(v_msg, p_expected) > 0, 'PASS', 'FAIL'),
                      CONCAT('refused: "', p_expected, '"'), v_msg);
    END IF;
END$$

-- THE ACCEPTED PATH: the statement must go through without an error
DROP PROCEDURE IF EXISTS t_ok$$
CREATE PROCEDURE t_ok(IN p_section VARCHAR(60), IN p_test VARCHAR(200), IN p_sql TEXT)
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    CALL t_record(p_section, p_test, IF(v_msg = '', 'PASS', 'FAIL'), 'accepted',
                  IF(v_msg = '', 'accepted', v_msg));
END$$

DELIMITER ;


-- #####################################################################
--  Everything from here is undone by the ROLLBACK below
-- #####################################################################
START TRANSACTION;

-- =====================================================================
--  SECTION 10 - 3.1.3.1  Assigning a vehicle to a trip
-- ---------------------------------------------------------------------
--  Procedure: sp_assign_vehicle_to_trip(trip, vehicle, current mileage)
--  The heart of the Trips screen ("Add Trip"). It runs five checks, prints
--  the result of every one of them as a PASS/FAIL table, and only if all
--  five pass does it attach the vehicle to the trip, set the vehicle to
--  InUse and record the new odometer reading.
--
--  Outcomes:
--    error   the trip does not exist                            (tested)
--    error   the vehicle does not exist                         (tested)
--    check 1 the vehicle must be Available   - Maintenance / InUse (both tested)
--    check 2 seats >= confirmed or paid reservations            (both ways tested)
--    check 3 more than 9 seats needs licence C or D - wrong licence,
--            no driver at all, and the case where 9 seats or fewer
--            make the licence irrelevant                        (all tested)
--    check 4 the vehicle is free on those dates - and trips that are
--            CANCELLED or COMPLETED do not count as a clash      (both tested)
--    check 5 the odometer may not go backwards - lower is refused,
--            equal is accepted                                  (both tested)
--    success everything passes and the data is written           (tested)
--    several checks may fail at once and all reasons are listed  (tested)
--
--  Seed data used here: trip 14 (Jan 2027, driver AT113 licence D),
--  vehicle 9 (52-seat bus, Available, 90 000 km), vehicle 4 (Maintenance),
--  trip 8 (driver AT114 licence B), vehicle 8 (9-seat van, 20 000 km).
-- =====================================================================

-- --- the two "does not exist" errors -----------------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'the trip must exist',
    'CALL sp_assign_vehicle_to_trip(9999, 1, 1)', 'trip does not exist');
CALL t_error('10. 3.1.3.1 vehicle', 'the vehicle must exist',
    'CALL sp_assign_vehicle_to_trip(1, 9999, 1)', 'vehicle does not exist');

-- --- check 1: the vehicle has to be free -------------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'check 1 FAILS: the vehicle is in Maintenance',
    'CALL sp_assign_vehicle_to_trip(1, 4, 200100)', 'vehicle is Maintenance');
UPDATE vehicle SET v_status = 'InUse' WHERE v_id = 6;
CALL t_error('10. 3.1.3.1 vehicle', 'check 1 FAILS: the vehicle is already InUse',
    'CALL sp_assign_vehicle_to_trip(13, 6, 120000)', 'vehicle is InUse');
UPDATE vehicle SET v_status = 'Available' WHERE v_id = 6;

-- --- check 2: enough seats for the people who booked -------------------
UPDATE vehicle SET v_seats = 2 WHERE v_id = 10;
CALL t_error('10. 3.1.3.1 vehicle', 'check 2 FAILS: 2 seats for 3 paid reservations',
    'CALL sp_assign_vehicle_to_trip(3, 10, 10100)', '2 seats < 3 reservations');
UPDATE vehicle SET v_seats = 5 WHERE v_id = 10;

-- --- check 3: the licence of the driver --------------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'check 3 FAILS: licence B may not drive a 50-seat bus',
    'CALL sp_assign_vehicle_to_trip(8, 1, 150100)', 'driver licence B (C/D needed)');
-- a trip that has no driver yet cannot take a bus either
INSERT INTO trip (tr_departure, tr_return, tr_maxseats, tr_cost_adult, tr_cost_child,
                  tr_status, tr_min_participants, tr_br_code, tr_drv_AT)
VALUES ('2027-07-01', '2027-07-05', 40, 100, 50, 'PLANNED', 2, 1, NULL);
SET @no_driver_trip = LAST_INSERT_ID();
CALL t_error('10. 3.1.3.1 vehicle', 'check 3 FAILS: a trip with no driver may not take a bus',
    CONCAT('CALL sp_assign_vehicle_to_trip(', @no_driver_trip, ', 9, 90000)'),
    'driver licence missing (C/D needed)');
DELETE FROM trip WHERE tr_id = @no_driver_trip;
-- with 9 seats or fewer the licence does not matter: trip 8's driver holds B
CALL t_ok('10. 3.1.3.1 vehicle', 'check 3 PASSES: licence B is fine for a 9-seat van',
    'CALL sp_assign_vehicle_to_trip(8, 8, 20000)');
CALL t_eq('10. 3.1.3.1 vehicle', 'check 5 PASSES: the same reading as recorded is accepted',
    (SELECT v_mileage FROM vehicle WHERE v_id = 8), '20000');
-- put it back for the checks that follow
UPDATE trip SET tr_vehicle_id = 8 WHERE tr_id = 8;
UPDATE vehicle SET v_status = 'Available' WHERE v_id = 8;

-- --- check 4: the vehicle must be free on those dates ------------------
CALL t_error('10. 3.1.3.1 vehicle', 'check 4 FAILS: the bus is on trip 1 during those days',
    'CALL sp_assign_vehicle_to_trip(2, 1, 150100)', 'overlaps 1 other trip');
-- a trip that was called off does not block its vehicle any more
UPDATE trip SET tr_status = 'CANCELLED' WHERE tr_id = 1;
CALL t_ok('10. 3.1.3.1 vehicle', 'check 4 PASSES: a CANCELLED trip does not block its vehicle',
    'CALL sp_assign_vehicle_to_trip(2, 1, 150100)');
UPDATE trip SET tr_status = 'PLANNED', tr_vehicle_id = 1 WHERE tr_id = 1;
UPDATE trip SET tr_vehicle_id = 2 WHERE tr_id = 2;
UPDATE vehicle SET v_status = 'Available', v_mileage = 150000 WHERE v_id = 1;

-- --- check 5: the odometer may not go backwards ------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'check 5 FAILS: a reading below the recorded one',
    'CALL sp_assign_vehicle_to_trip(14, 9, 1000)', 'mileage 1000 < recorded 90000');

-- --- several checks failing at once ------------------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'two checks fail: BOTH reasons are reported',
    'CALL sp_assign_vehicle_to_trip(1, 4, 1)',
    'vehicle is Maintenance; mileage 1 < recorded 200000');
CALL t_eq('10. 3.1.3.1 vehicle', 'a refused assignment changes nothing at all',
    (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 4), 'Maintenance/200000');

-- --- the assignment that passes every check ----------------------------
CALL t_ok('10. 3.1.3.1 vehicle', 'SUCCESS: all five checks pass, the vehicle is assigned',
    'CALL sp_assign_vehicle_to_trip(14, 9, 90500)');
CALL t_eq('10. 3.1.3.1 vehicle', 'SUCCESS: the vehicle is now InUse with the new reading',
    (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9), 'InUse/90500');
CALL t_eq('10. 3.1.3.1 vehicle', 'SUCCESS: the trip now points at the vehicle',
    (SELECT tr_vehicle_id FROM trip WHERE tr_id = 14), '9');
CALL t_has('10. 3.1.3.1 vehicle', 'SUCCESS: the change is written to the audit log',
    (SELECT log_details FROM log_actions WHERE log_table_name = 'vehicle' ORDER BY log_id DESC LIMIT 1),
    'status Available -> InUse, mileage 90000 -> 90500');


-- #####################################################################
--  Undo everything the checks did
-- #####################################################################
ROLLBACK;


-- #####################################################################
--  THE REPORT
-- #####################################################################

-- 1. every check, in order
SELECT id, section, test, status FROM test_results ORDER BY id;

-- 2. the failures on their own, with what was expected and what came back
SELECT id, section, test, expected, actual
FROM test_results WHERE status = 'FAIL' ORDER BY id;

-- 3. the summary
SELECT COUNT(*)             AS total,
       SUM(status = 'PASS') AS passed,
       SUM(status = 'FAIL') AS failed,
       IF(SUM(status = 'FAIL') = 0, 'ALL TESTS PASSED', 'THERE ARE FAILURES') AS result
FROM test_results;

-- 4. the proof that the database was left exactly as it was found
SELECT 'the tests changed nothing' AS note,
       (SELECT COUNT(*) FROM customer)    AS customers,
       (SELECT COUNT(*) FROM reservation) AS reservations,
       (SELECT COUNT(*) FROM room_usage)  AS room_usage_rows,
       (SELECT COUNT(*) FROM log_actions) AS log_rows,
       (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9) AS vehicle_9,
       (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101')                AS salary_AT101;


-- #####################################################################
--  Remove the harness again
-- #####################################################################
DROP PROCEDURE IF EXISTS t_record;
DROP PROCEDURE IF EXISTS t_eq;
DROP PROCEDURE IF EXISTS t_min;
DROP PROCEDURE IF EXISTS t_has;
DROP PROCEDURE IF EXISTS t_error;
DROP PROCEDURE IF EXISTS t_ok;
DROP TEMPORARY TABLE IF EXISTS test_results;
