-- #####################################################################
--  3.1.3.1_assign_vehicle.sql
--  3.1.3.1  Assigning a vehicle to a trip
-- #####################################################################
--  GENERATED from queries/Tests.sql (section 10) by
--  tests/split_sql_tests.sh - edit Tests.sql and run the script again,
--  do not edit this file by hand.
--
--  It runs on its own: it installs the small test harness, loads the
--  seed data of the report inside a transaction (so it passes whatever
--  was done in the GUI before), runs the checks of this one question,
--  rolls everything back and prints a PASS/FAIL report. It changes
--  nothing.
--  (The client warns about a non-transactional table at the end: that
--  is the MEMORY table that carries the report through the rollback.)
--
--  Run it with
--    docker exec -i baseis-mariadb mariadb -uroot -pjohn2005 -t baseisproject < queries/tests/3.1.3.1_assign_vehicle.sql
--  or open it in a SQL client and execute the whole file.
-- #####################################################################

-- #####################################################################
--  THE TEST HARNESS
--  Six helper procedures record one line per check instead of stopping at
--  the first failure, so one run reports everything at once.
--  They are dropped again at the end of the file.
-- #####################################################################

DROP TEMPORARY TABLE IF EXISTS test_results;
CREATE TEMPORARY TABLE test_results (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    section  VARCHAR(60),
    test     VARCHAR(200),
    status   VARCHAR(4),
    expected VARCHAR(255),
    actual   VARCHAR(255)
) ENGINE = MEMORY;   -- MEMORY is not transactional: the report survives the ROLLBACK

DELIMITER $$

-- write one line of the report
DROP PROCEDURE IF EXISTS t_record$$
CREATE PROCEDURE t_record(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                          IN p_status VARCHAR(4), IN p_expected VARCHAR(255), IN p_actual VARCHAR(255))
BEGIN
    INSERT INTO test_results (section, test, status, expected, actual)
    VALUES (p_section, p_test, p_status, LEFT(p_expected, 255), LEFT(p_actual, 255));
END$$

-- the value must be exactly the expected one
DROP PROCEDURE IF EXISTS t_eq$$
CREATE PROCEDURE t_eq(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                      IN p_actual TEXT, IN p_expected TEXT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual <=> p_expected, 'PASS', 'FAIL'),
                  IFNULL(p_expected, 'NULL'), IFNULL(p_actual, 'NULL'));
END$$

-- the value must be at least the expected minimum (the row counts of 3.1.1)
DROP PROCEDURE IF EXISTS t_min$$
CREATE PROCEDURE t_min(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual BIGINT, IN p_min BIGINT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual >= p_min, 'PASS', 'FAIL'),
                  CONCAT('>= ', p_min), CAST(p_actual AS CHAR));
END$$

-- the value must contain the expected text
DROP PROCEDURE IF EXISTS t_has$$
CREATE PROCEDURE t_has(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual TEXT, IN p_expected VARCHAR(255))
BEGIN
    CALL t_record(p_section, p_test,
                  IF(INSTR(IFNULL(p_actual, ''), p_expected) > 0, 'PASS', 'FAIL'),
                  CONCAT('contains "', p_expected, '"'), IFNULL(p_actual, 'NULL'));
END$$

-- THE REFUSED PATH: the statement must fail, with a message we expect.
-- The handler catches the SIGNAL raised by a trigger or a procedure, so the
-- suite can carry on and report it as a passing test.
DROP PROCEDURE IF EXISTS t_error$$
CREATE PROCEDURE t_error(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                         IN p_sql TEXT, IN p_expected VARCHAR(255))
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    IF v_msg = '' THEN
        CALL t_record(p_section, p_test, 'FAIL',
                      CONCAT('refused: "', p_expected, '"'), 'the statement was ACCEPTED');
    ELSE
        CALL t_record(p_section, p_test, IF(INSTR(v_msg, p_expected) > 0, 'PASS', 'FAIL'),
                      CONCAT('refused: "', p_expected, '"'), v_msg);
    END IF;
END$$

-- THE ACCEPTED PATH: the statement must go through without an error
DROP PROCEDURE IF EXISTS t_ok$$
CREATE PROCEDURE t_ok(IN p_section VARCHAR(60), IN p_test VARCHAR(200), IN p_sql TEXT)
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    CALL t_record(p_section, p_test, IF(v_msg = '', 'PASS', 'FAIL'), 'accepted',
                  IF(v_msg = '', 'accepted', v_msg));
END$$

-- THE STARTING POINT: the seed data of the report, loaded inside the
-- transaction. Whatever was clicked in the GUI before (a new trip, a bus
-- taken, hotels booked, salaries changed), the checks always start from the
-- same data - and the ROLLBACK at the end puts the GUI's data back exactly
-- as it was. The procedures and triggers under test are the real ones; only
-- the rows are reset. trip_history is not touched (it never changes).
-- The rows below are generated from baseisproject_dump.sql by
-- tests/split_sql_tests.sh, so they are always the rows of the demo state.
DROP PROCEDURE IF EXISTS t_fixture$$
CREATE PROCEDURE t_fixture()
BEGIN
    -- the log triggers need the current account to be a registered DBA
    INSERT IGNORE INTO dba_users (dba_username, dba_start_date)
    VALUES (SUBSTRING_INDEX(USER(), '@', 1), CURDATE());

    SET FOREIGN_KEY_CHECKS = 0;
    -- BEGIN FIXTURE ROWS (generated - do not edit by hand)
    DELETE FROM `admin`;
    INSERT INTO `admin` VALUES
    ('AT101','ADMINISTRATIVE','MBA'),
    ('AT102','ACCOUNTING','Econ'),
    ('AT103','LOGISTICS','Logistics'),
    ('AT104','ADMINISTRATIVE','BSc'),
    ('AT105','LOGISTICS','MSc'),
    ('AT106','ACCOUNTING','PhD'),
    ('AT107','ADMINISTRATIVE','Diploma'),
    ('AT108','LOGISTICS','Cert'),
    ('AT109','ACCOUNTING','BSc'),
    ('AT110','ADMINISTRATIVE','MBA');
    DELETE FROM `branch`;
    INSERT INTO `branch` VALUES
    (1,'Panepistimiou',56,'Athens','AT101'),
    (2,'Tsimiski',22,'Thessaloniki','AT102'),
    (3,'Maizonos',10,'Patras','AT103'),
    (4,'Dikaiosinis',5,'Heraklion','AT104'),
    (5,'Dodonis',33,'Ioannina','AT105'),
    (6,'Farsalon',12,'Larisa','AT106');
    DELETE FROM `customer`;
    INSERT INTO `customer` VALUES
    (1,'C1','Lname1','c1.lname1@mail.com','6901','Street 1, City 2','1980-07-30'),
    (2,'C2','Lname2','c2.lname2@mail.com','6902','Street 2, City 3','1981-02-26'),
    (3,'C3','Lname3','c3.lname3@mail.com','6903','Street 3, City 4','1981-09-25'),
    (4,'C4','Lname4','c4.lname4@mail.com','6904','Street 4, City 5','1982-04-24'),
    (5,'C5','Lname5','c5.lname5@mail.com','6905','Street 5, City 1','1982-11-21'),
    (6,'C6','Lname6','c6.lname6@mail.com','6906','Street 6, City 2','1983-06-20'),
    (7,'C7','Lname7','c7.lname7@mail.com','6907','Street 7, City 3','1984-01-17'),
    (8,'C8','Lname8','c8.lname8@mail.com','6908','Street 8, City 4','1984-08-15'),
    (9,'C9','Lname9','c9.lname9@mail.com','6909','Street 9, City 5','1985-03-14'),
    (10,'C10','Lname10','c10.lname10@mail.com','6910','Street 10, City 1','1985-10-11'),
    (11,'C11','Lname11','c11.lname11@mail.com','6911','Street 11, City 2','1986-05-10'),
    (12,'C12','Lname12','c12.lname12@mail.com','6912','Street 12, City 3','1986-12-07'),
    (13,'C13','Lname13','c13.lname13@mail.com','6913','Street 13, City 4','1987-07-06'),
    (14,'C14','Lname14','c14.lname14@mail.com','6914','Street 14, City 5','1988-02-02'),
    (15,'C15','Lname15','c15.lname15@mail.com','6915','Street 15, City 1','1988-08-31'),
    (16,'C16','Lname16','c16.lname16@mail.com','6916','Street 16, City 2','2019-04-02'),
    (17,'C17','Lname17','c17.lname17@mail.com','6917','Street 17, City 3','2019-07-08'),
    (18,'C18','Lname18','c18.lname18@mail.com','6918','Street 18, City 4','2019-10-13'),
    (19,'C19','Lname19','c19.lname19@mail.com','6919','Street 19, City 5','2015-02-13'),
    (20,'C20','Lname20','c20.lname20@mail.com','6920','Street 20, City 1','2015-05-21');
    DELETE FROM `destination`;
    INSERT INTO `destination` VALUES
    (1,'Paris','France','ABROAD','FR',11),
    (2,'London','UK','ABROAD','EN',NULL),
    (3,'Berlin','Germany','ABROAD','DE',NULL),
    (4,'Rome','Italy','ABROAD','IT',NULL),
    (5,'Madrid','Spain','ABROAD','ES',NULL),
    (6,'Nafplio','Peloponnese','LOCAL','GR',NULL),
    (7,'Meteora','Thessaly','LOCAL','GR',NULL),
    (8,'Delphi','Central Greece','LOCAL','GR',NULL),
    (9,'New York','USA','ABROAD','EN',NULL),
    (10,'Tokyo','Japan','ABROAD','EN',NULL),
    (11,'France','Country','ABROAD','FR',NULL);
    DELETE FROM `driver`;
    INSERT INTO `driver` VALUES
    ('AT111','D','ABROAD',10),
    ('AT112','C','ABROAD',5),
    ('AT113','D','ABROAD',12),
    ('AT114','B','LOCAL',3),
    ('AT115','D','ABROAD',8),
    ('AT116','C','LOCAL',4),
    ('AT117','D','ABROAD',15),
    ('AT118','B','LOCAL',2);
    DELETE FROM `event`;
    INSERT INTO `event` VALUES
    (1,'2026-06-02 10:00:00','2026-06-02 12:00:00','Museum'),
    (1,'2026-06-03 18:00:00','2026-06-03 20:00:00','Dinner'),
    (2,'2026-06-06 10:00:00','2026-06-06 12:00:00','Walk'),
    (2,'2026-06-07 18:00:00','2026-06-07 20:00:00','Show'),
    (3,'2026-06-11 10:00:00','2026-06-11 12:00:00','Tour'),
    (3,'2026-06-12 18:00:00','2026-06-12 20:00:00','Party'),
    (4,'2026-07-02 10:00:00','2026-07-02 12:00:00','Visit'),
    (4,'2026-07-03 18:00:00','2026-07-03 20:00:00','Eat'),
    (5,'2026-07-06 10:00:00','2026-07-06 12:00:00','Swim'),
    (5,'2026-07-07 18:00:00','2026-07-07 20:00:00','Drink'),
    (6,'2026-07-16 10:00:00','2026-07-16 12:00:00','Run'),
    (6,'2026-07-17 18:00:00','2026-07-17 20:00:00','Sleep'),
    (7,'2026-08-02 10:00:00','2026-08-02 12:00:00','Hike'),
    (7,'2026-08-03 18:00:00','2026-08-03 20:00:00','Camp'),
    (8,'2026-08-11 10:00:00','2026-08-11 12:00:00','Drive'),
    (8,'2026-08-12 18:00:00','2026-08-12 20:00:00','Stop'),
    (9,'2026-09-02 10:00:00','2026-09-02 12:00:00','Fly'),
    (9,'2026-09-03 18:00:00','2026-09-03 20:00:00','Land'),
    (10,'2026-09-16 09:00:00','2026-09-16 12:00:00','Manhattan walking tour'),
    (11,'2026-10-02 10:00:00','2026-10-02 13:00:00','Louvre visit'),
    (12,'2026-11-02 10:00:00','2026-11-02 12:00:00','Thames boat tour'),
    (13,'2026-12-21 10:00:00','2026-12-21 13:00:00','Christmas market walk'),
    (14,'2027-01-06 10:00:00','2027-01-06 12:30:00','Guided city tour');
    DELETE FROM `guide`;
    INSERT INTO `guide` VALUES
    ('AT119','Art Hist'),
    ('AT120','Arch'),
    ('AT121','Lang'),
    ('AT122','Hist'),
    ('AT123','Geog'),
    ('AT124','Culture'),
    ('AT125','Nature'),
    ('AT126','Food');
    DELETE FROM `language_ref`;
    INSERT INTO `language_ref` VALUES
    ('DE','German'),
    ('EN','English'),
    ('ES','Spanish'),
    ('FR','French'),
    ('GR','Greek'),
    ('IT','Italian');
    DELETE FROM `languages`;
    INSERT INTO `languages` VALUES
    ('AT121','DE'),
    ('AT120','EN'),
    ('AT125','EN'),
    ('AT123','ES'),
    ('AT119','FR'),
    ('AT126','FR'),
    ('AT124','GR'),
    ('AT122','IT');
    DELETE FROM `lodging`;
    INSERT INTO `lodging` VALUES
    (1,1,'Le Grand Paris','Hotel',5,4.80,'Active','10 Rue de Rivoli','Paris','75001','3310000001','contact@grandparis.fr',100,250.00,1,1,1,1),
    (2,2,'London Stay','Hostel',NULL,3.50,'Active','22 Baker St','London','NW1 6XE','4420000002','info@londonstay.uk',30,60.00,1,0,0,0),
    (3,3,'Berlin Plaza','Hotel',4,4.20,'Active','Alexanderplatz 1','Berlin','10178','4930000003','booking@berlinplaza.de',80,120.00,1,1,1,1),
    (4,4,'Roma Bella','Apartment',NULL,4.90,'Active','Via Roma 10','Rome','00184','3906000004','hello@romabella.it',5,150.00,1,0,1,0),
    (5,5,'Madrid Sol','Hotel',3,4.00,'Active','Puerta del Sol','Madrid','28013','3491000005','reception@madridsol.es',50,90.00,1,0,1,1),
    (6,6,'Nafplio Palace','Resort',5,4.70,'Active','Acronafplia','Nafplio','21100','3027520006','reservations@nafplio.gr',60,200.00,1,1,1,1),
    (7,7,'Meteora View','Room',NULL,4.50,'Active','Kalambaka Main Rd','Kalambaka','42200','3024320007','rooms@meteora.gr',10,50.00,0,0,1,0),
    (8,8,'Delphi Omni','Hotel',3,3.80,'Active','Apollonos St','Delphi','33054','3022650008','info@delphiomni.gr',40,80.00,1,1,1,0),
    (9,9,'NYC Central','Hotel',4,4.30,'Active','5th Avenue','New York','10118','1212000009','stay@nyccentral.us',200,300.00,1,1,1,1),
    (10,10,'Tokyo Capsule','Hostel',NULL,4.10,'Active','Shinjuku','Tokyo','160-0022','8130000010','sleep@tokyo.jp',500,40.00,1,0,1,1);
    DELETE FROM `manages`;
    INSERT INTO `manages` VALUES
    ('AT101',1),
    ('AT102',2),
    ('AT103',3),
    ('AT104',4),
    ('AT105',5),
    ('AT106',6);
    DELETE FROM `phones`;
    INSERT INTO `phones` VALUES
    (1,'2101234567'),
    (1,'2107654321'),
    (1,'2109990000'),
    (2,'2310123456'),
    (2,'2310888777'),
    (2,'2310999888'),
    (3,'2610111222'),
    (4,'2810333444'),
    (5,'2651055566'),
    (6,'2410777888');
    DELETE FROM `reservation`;
    INSERT INTO `reservation` VALUES
    (1,1,1,'CONFIRMED',500.00),
    (1,2,2,'CONFIRMED',500.00),
    (1,3,3,'PENDING',500.00),
    (2,1,4,'CONFIRMED',400.00),
    (2,2,5,'PAID',400.00),
    (3,1,6,'PAID',600.00),
    (3,2,7,'PAID',600.00),
    (3,3,8,'PAID',600.00),
    (4,1,9,'CONFIRMED',300.00),
    (5,1,10,'CONFIRMED',550.00),
    (5,2,11,'CONFIRMED',550.00),
    (6,1,12,'PAID',250.00),
    (7,1,13,'CONFIRMED',450.00),
    (7,2,14,'CONFIRMED',450.00),
    (8,1,15,'CONFIRMED',350.00),
    (9,1,16,'CONFIRMED',350.00),
    (9,2,17,'PENDING',350.00),
    (10,1,18,'PAID',100.00),
    (11,1,19,'CONFIRMED',250.00),
    (12,1,20,'CONFIRMED',150.00),
    (13,1,1,'PAID',800.00),
    (13,2,2,'PAID',800.00),
    (14,1,3,'CONFIRMED',600.00),
    (14,2,4,'PENDING',600.00);
    DELETE FROM `room_usage`;
    DELETE FROM `travel_to`;
    INSERT INTO `travel_to` VALUES
    (1,1,1,'2026-06-01 14:00:00','2026-06-05 11:00:00'),
    (1,2,2,'2026-06-05 14:00:00','2026-06-10 11:00:00'),
    (2,2,1,'2026-06-05 14:00:00','2026-06-09 11:00:00'),
    (2,3,2,'2026-06-09 14:00:00','2026-06-12 11:00:00'),
    (3,3,1,'2026-06-10 14:00:00','2026-06-13 11:00:00'),
    (3,4,2,'2026-06-13 14:00:00','2026-06-15 11:00:00'),
    (4,4,1,'2026-07-01 14:00:00','2026-07-03 11:00:00'),
    (4,5,2,'2026-07-03 14:00:00','2026-07-05 11:00:00'),
    (5,5,1,'2026-07-05 14:00:00','2026-07-10 11:00:00'),
    (6,6,1,'2026-07-15 14:00:00','2026-07-20 11:00:00'),
    (7,7,1,'2026-08-01 14:00:00','2026-08-08 11:00:00'),
    (8,8,1,'2026-08-10 14:00:00','2026-08-15 11:00:00'),
    (9,9,1,'2026-09-01 14:00:00','2026-09-10 11:00:00'),
    (10,10,1,'2026-09-15 14:00:00','2026-09-20 11:00:00'),
    (11,1,1,'2026-10-01 14:00:00','2026-10-10 11:00:00'),
    (12,2,1,'2026-11-01 14:00:00','2026-11-05 11:00:00'),
    (13,3,1,'2026-12-20 14:00:00','2026-12-27 11:00:00'),
    (14,4,1,'2027-01-05 14:00:00','2027-01-10 11:00:00');
    DELETE FROM `trip`;
    INSERT INTO `trip` VALUES
    (1,'2026-06-01 00:00:00','2026-06-10 00:00:00',50,500.00,300.00,'PLANNED',10,1,'AT119','AT111',1,0),
    (2,'2026-06-05 00:00:00','2026-06-12 00:00:00',20,400.00,200.00,'CONFIRMED',4,1,'AT120','AT112',2,0),
    (3,'2026-06-10 00:00:00','2026-06-15 00:00:00',50,600.00,350.00,'COMPLETED',10,2,'AT121','AT113',4,0),
    (4,'2026-07-01 00:00:00','2026-07-05 00:00:00',9,300.00,150.00,'PLANNED',2,2,'AT122','AT117',3,0),
    (5,'2026-07-05 00:00:00','2026-07-10 00:00:00',60,550.00,275.00,'PLANNED',12,3,'AT123','AT115',6,0),
    (6,'2026-07-15 00:00:00','2026-07-20 00:00:00',8,250.00,125.00,'COMPLETED',2,3,'AT124','AT116',5,0),
    (7,'2026-08-01 00:00:00','2026-08-08 00:00:00',18,450.00,225.00,'PLANNED',3,4,'AT125','AT116',7,0),
    (8,'2026-08-10 00:00:00','2026-08-15 00:00:00',9,350.00,175.00,'CONFIRMED',2,5,'AT126','AT114',8,0),
    (9,'2026-09-01 00:00:00','2026-09-10 00:00:00',52,700.00,350.00,'PLANNED',10,6,'AT119','AT111',9,0),
    (10,'2026-09-15 00:00:00','2026-09-20 00:00:00',5,200.00,100.00,'COMPLETED',2,1,'AT120','AT111',10,0),
    (11,'2026-10-01 00:00:00','2026-10-10 00:00:00',50,500.00,250.00,'PLANNED',10,1,'AT121','AT112',1,0),
    (12,'2026-11-01 00:00:00','2026-11-05 00:00:00',20,300.00,150.00,'PLANNED',4,2,'AT122','AT113',2,0),
    (13,'2026-12-20 00:00:00','2026-12-27 00:00:00',50,800.00,400.00,'PLANNED',10,3,'AT123','AT115',6,0),
    (14,'2027-01-05 00:00:00','2027-01-10 00:00:00',50,600.00,300.00,'PLANNED',10,4,'AT124','AT113',9,0);
    DELETE FROM `vehicle`;
    INSERT INTO `vehicle` VALUES
    (1,1,'IAA-1001','Tourismo','Mercedes','Bus',50,'Available',150000),
    (2,1,'IAA-1002','Sprinter','Mercedes','Mini-Bus',20,'Available',80000),
    (3,2,'IBB-2001','Transit','Ford','Van',9,'Available',45000),
    (4,2,'IBB-2002','Irizar','Scania','Bus',55,'Maintenance',200000),
    (5,3,'ICC-3001','Vito','Mercedes','Van',8,'Available',30000),
    (6,3,'ICC-3002','Setra','Setra','Bus',60,'Available',120000),
    (7,4,'IDD-4001','Daily','Iveco','Mini-Bus',18,'Available',50000),
    (8,5,'IEE-5001','Traveller','Peugeot','Van',9,'Available',20000),
    (9,6,'IFF-6001','Lion','Man','Bus',52,'Available',90000),
    (10,1,'IAA-1003','Yaris','Toyota','Car',5,'Available',10000);
    DELETE FROM `worker`;
    INSERT INTO `worker` VALUES
    ('AT101','Nikos','Papadopoulos','nikos@ag.gr',1500.00,1),
    ('AT102','Maria','Georgiou','maria@ag.gr',1400.00,2),
    ('AT103','Yannis','Dimitriou','yannis@ag.gr',1400.00,3),
    ('AT104','Eleni','Alexiou','eleni@ag.gr',1400.00,4),
    ('AT105','Kostas','Kostas','kostas@ag.gr',1400.00,5),
    ('AT106','Anna','Vissi','anna@ag.gr',1400.00,6),
    ('AT107','Giorgos','Mazon','giorgos@ag.gr',1200.00,1),
    ('AT108','Despina','Vandi','despina@ag.gr',1200.00,1),
    ('AT109','Sakis','Rouvas','sakis@ag.gr',1200.00,2),
    ('AT110','Helena','Rizou','helena@ag.gr',1200.00,2),
    ('AT111','Takis','Volanis','takis@ag.gr',1000.00,1),
    ('AT112','Makis','Dimas','makis@ag.gr',1000.00,1),
    ('AT113','Lakis','Lazopoulos','lakis@ag.gr',1000.00,2),
    ('AT114','Akis','Petretzikis','akis@ag.gr',1000.00,2),
    ('AT115','Sakis','Boulas','sb@ag.gr',1000.00,3),
    ('AT116','Vakis','Vakakis','vv@ag.gr',1000.00,4),
    ('AT117','Mimis','Plessas','mp@ag.gr',1000.00,5),
    ('AT118','Babis','Stokas','bs@ag.gr',1000.00,6),
    ('AT119','Zoi','Laskari','zoi@ag.gr',1100.00,1),
    ('AT120','Aliki','Vougiou','aliki@ag.gr',1100.00,1),
    ('AT121','Tzeni','Karezi','tzeni@ag.gr',1100.00,2),
    ('AT122','Rena','Vlachop','rena@ag.gr',1100.00,3),
    ('AT123','Dinos','Iliop','dinos@ag.gr',1100.00,4),
    ('AT124','Thanasis','Veggos','than@ag.gr',1100.00,5),
    ('AT125','Lambros','Konstan','lam@ag.gr',1100.00,6),
    ('AT126','Kostas','Voutsas','kv@ag.gr',1100.00,1);
    -- END FIXTURE ROWS
    SET FOREIGN_KEY_CHECKS = 1;

    -- the seed rows above went through the log triggers too; start clean
    DELETE FROM log_actions;
END$$

DELIMITER ;


-- #####################################################################
--  Everything from here is undone by the ROLLBACK below
-- #####################################################################
START TRANSACTION;

-- start from the seed data of the report, whatever the GUI did before
CALL t_fixture();

-- =====================================================================
--  SECTION 10 - 3.1.3.1  Assigning a vehicle to a trip
-- ---------------------------------------------------------------------
--  Procedure: sp_assign_vehicle_to_trip(trip, vehicle, current mileage)
--  The heart of the Trips screen ("Add Trip"). It runs five checks, prints
--  the result of every one of them as a PASS/FAIL table, and only if all
--  five pass does it attach the vehicle to the trip, set the vehicle to
--  InUse and record the new odometer reading.
--
--  Outcomes:
--    error   the trip does not exist                            (tested)
--    error   the vehicle does not exist                         (tested)
--    check 1 the vehicle must be Available   - Maintenance / InUse (both tested)
--    check 2 seats >= confirmed or paid reservations            (both ways tested)
--    check 3 more than 9 seats needs licence C or D - wrong licence,
--            no driver at all, and the case where 9 seats or fewer
--            make the licence irrelevant                        (all tested)
--    check 4 the vehicle is free on those dates - and trips that are
--            CANCELLED or COMPLETED do not count as a clash      (both tested)
--    check 5 the odometer may not go backwards - lower is refused,
--            equal is accepted                                  (both tested)
--    success everything passes and the data is written           (tested)
--    several checks may fail at once and all reasons are listed  (tested)
--
--  Seed data used here: trip 14 (Jan 2027, driver AT113 licence D),
--  vehicle 9 (52-seat bus, Available, 90 000 km), vehicle 4 (Maintenance),
--  trip 8 (driver AT114 licence B), vehicle 8 (9-seat van, 20 000 km).
-- =====================================================================

-- --- the two "does not exist" errors -----------------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'the trip must exist',
    'CALL sp_assign_vehicle_to_trip(9999, 1, 1)', 'trip does not exist');
CALL t_error('10. 3.1.3.1 vehicle', 'the vehicle must exist',
    'CALL sp_assign_vehicle_to_trip(1, 9999, 1)', 'vehicle does not exist');

-- --- check 1: the vehicle has to be free -------------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'check 1 FAILS: the vehicle is in Maintenance',
    'CALL sp_assign_vehicle_to_trip(1, 4, 200100)', 'vehicle is Maintenance');
UPDATE vehicle SET v_status = 'InUse' WHERE v_id = 6;
CALL t_error('10. 3.1.3.1 vehicle', 'check 1 FAILS: the vehicle is already InUse',
    'CALL sp_assign_vehicle_to_trip(13, 6, 120000)', 'vehicle is InUse');
UPDATE vehicle SET v_status = 'Available' WHERE v_id = 6;

-- --- check 2: enough seats for the people who booked -------------------
UPDATE vehicle SET v_seats = 2 WHERE v_id = 10;
CALL t_error('10. 3.1.3.1 vehicle', 'check 2 FAILS: 2 seats for 3 paid reservations',
    'CALL sp_assign_vehicle_to_trip(3, 10, 10100)', '2 seats < 3 reservations');
UPDATE vehicle SET v_seats = 5 WHERE v_id = 10;

-- --- check 3: the licence of the driver --------------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'check 3 FAILS: licence B may not drive a 50-seat bus',
    'CALL sp_assign_vehicle_to_trip(8, 1, 150100)', 'driver licence B (C/D needed)');
-- a trip that has no driver yet cannot take a bus either
INSERT INTO trip (tr_departure, tr_return, tr_maxseats, tr_cost_adult, tr_cost_child,
                  tr_status, tr_min_participants, tr_br_code, tr_drv_AT)
VALUES ('2027-07-01', '2027-07-05', 40, 100, 50, 'PLANNED', 2, 1, NULL);
SET @no_driver_trip = LAST_INSERT_ID();
CALL t_error('10. 3.1.3.1 vehicle', 'check 3 FAILS: a trip with no driver may not take a bus',
    CONCAT('CALL sp_assign_vehicle_to_trip(', @no_driver_trip, ', 9, 90000)'),
    'driver licence missing (C/D needed)');
DELETE FROM trip WHERE tr_id = @no_driver_trip;
-- with 9 seats or fewer the licence does not matter: trip 8's driver holds B
CALL t_ok('10. 3.1.3.1 vehicle', 'check 3 PASSES: licence B is fine for a 9-seat van',
    'CALL sp_assign_vehicle_to_trip(8, 8, 20000)');
CALL t_eq('10. 3.1.3.1 vehicle', 'check 5 PASSES: the same reading as recorded is accepted',
    (SELECT v_mileage FROM vehicle WHERE v_id = 8), '20000');
-- put it back for the checks that follow
UPDATE trip SET tr_vehicle_id = 8 WHERE tr_id = 8;
UPDATE vehicle SET v_status = 'Available' WHERE v_id = 8;

-- --- check 4: the vehicle must be free on those dates ------------------
CALL t_error('10. 3.1.3.1 vehicle', 'check 4 FAILS: the bus is on trip 1 during those days',
    'CALL sp_assign_vehicle_to_trip(2, 1, 150100)', 'overlaps 1 other trip');
-- a trip that was called off does not block its vehicle any more
UPDATE trip SET tr_status = 'CANCELLED' WHERE tr_id = 1;
CALL t_ok('10. 3.1.3.1 vehicle', 'check 4 PASSES: a CANCELLED trip does not block its vehicle',
    'CALL sp_assign_vehicle_to_trip(2, 1, 150100)');
UPDATE trip SET tr_status = 'PLANNED', tr_vehicle_id = 1 WHERE tr_id = 1;
UPDATE trip SET tr_vehicle_id = 2 WHERE tr_id = 2;
UPDATE vehicle SET v_status = 'Available', v_mileage = 150000 WHERE v_id = 1;

-- --- check 5: the odometer may not go backwards ------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'check 5 FAILS: a reading below the recorded one',
    'CALL sp_assign_vehicle_to_trip(14, 9, 1000)', 'mileage 1000 < recorded 90000');

-- --- several checks failing at once ------------------------------------
CALL t_error('10. 3.1.3.1 vehicle', 'two checks fail: BOTH reasons are reported',
    'CALL sp_assign_vehicle_to_trip(1, 4, 1)',
    'vehicle is Maintenance; mileage 1 < recorded 200000');
CALL t_eq('10. 3.1.3.1 vehicle', 'a refused assignment changes nothing at all',
    (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 4), 'Maintenance/200000');

-- --- the assignment that passes every check ----------------------------
CALL t_ok('10. 3.1.3.1 vehicle', 'SUCCESS: all five checks pass, the vehicle is assigned',
    'CALL sp_assign_vehicle_to_trip(14, 9, 90500)');
CALL t_eq('10. 3.1.3.1 vehicle', 'SUCCESS: the vehicle is now InUse with the new reading',
    (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9), 'InUse/90500');
CALL t_eq('10. 3.1.3.1 vehicle', 'SUCCESS: the trip now points at the vehicle',
    (SELECT tr_vehicle_id FROM trip WHERE tr_id = 14), '9');
CALL t_has('10. 3.1.3.1 vehicle', 'SUCCESS: the change is written to the audit log',
    (SELECT log_details FROM log_actions WHERE log_table_name = 'vehicle' ORDER BY log_id DESC LIMIT 1),
    'status Available -> InUse, mileage 90000 -> 90500');


-- #####################################################################
--  Undo everything the checks did
-- #####################################################################
ROLLBACK;


-- #####################################################################
--  THE REPORT
-- #####################################################################

-- 1. every check, in order
SELECT id, section, test, status FROM test_results ORDER BY id;

-- 2. the failures on their own, with what was expected and what came back
SELECT id, section, test, expected, actual
FROM test_results WHERE status = 'FAIL' ORDER BY id;

-- 3. the summary
SELECT COUNT(*)             AS total,
       SUM(status = 'PASS') AS passed,
       SUM(status = 'FAIL') AS failed,
       IF(SUM(status = 'FAIL') = 0, 'ALL TESTS PASSED', 'THERE ARE FAILURES') AS result
FROM test_results;

-- 4. the proof that the database was left exactly as it was found
SELECT 'the tests changed nothing' AS note,
       (SELECT COUNT(*) FROM customer)    AS customers,
       (SELECT COUNT(*) FROM reservation) AS reservations,
       (SELECT COUNT(*) FROM room_usage)  AS room_usage_rows,
       (SELECT COUNT(*) FROM log_actions) AS log_rows,
       (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9) AS vehicle_9,
       (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101')                AS salary_AT101;


-- #####################################################################
--  Remove the harness again
-- #####################################################################
DROP PROCEDURE IF EXISTS t_record;
DROP PROCEDURE IF EXISTS t_eq;
DROP PROCEDURE IF EXISTS t_min;
DROP PROCEDURE IF EXISTS t_has;
DROP PROCEDURE IF EXISTS t_error;
DROP PROCEDURE IF EXISTS t_ok;
DROP PROCEDURE IF EXISTS t_fixture;
DROP TEMPORARY TABLE IF EXISTS test_results;
