-- #####################################################################
--  3.1.3.3_book_whole_trip.sql
--  3.1.3.3  Booking the accommodation of a whole trip
-- #####################################################################
--  GENERATED from queries/Tests.sql (section 9) by
--  tests/split_sql_tests.sh - edit Tests.sql and run the script again,
--  do not edit this file by hand.
--
--  It runs on its own: it installs the small test harness, runs the
--  checks of this one question inside a transaction, rolls everything
--  back and prints a PASS/FAIL report. It changes nothing.
--  (The client warns about a non-transactional table at the end: that
--  is the MEMORY table that carries the report through the rollback.)
--
--  Run it with
--    docker exec -i baseis-mariadb mariadb -uroot -pjohn2005 -t baseisproject < queries/tests/3.1.3.3_book_whole_trip.sql
--  or open it in a SQL client and execute the whole file.
-- #####################################################################

-- #####################################################################
--  THE TEST HARNESS
--  Six helper procedures record one line per check instead of stopping at
--  the first failure, so one run reports everything at once.
--  They are dropped again at the end of the file.
-- #####################################################################

DROP TEMPORARY TABLE IF EXISTS test_results;
CREATE TEMPORARY TABLE test_results (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    section  VARCHAR(60),
    test     VARCHAR(200),
    status   VARCHAR(4),
    expected VARCHAR(255),
    actual   VARCHAR(255)
) ENGINE = MEMORY;   -- MEMORY is not transactional: the report survives the ROLLBACK

DELIMITER $$

-- write one line of the report
DROP PROCEDURE IF EXISTS t_record$$
CREATE PROCEDURE t_record(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                          IN p_status VARCHAR(4), IN p_expected VARCHAR(255), IN p_actual VARCHAR(255))
BEGIN
    INSERT INTO test_results (section, test, status, expected, actual)
    VALUES (p_section, p_test, p_status, LEFT(p_expected, 255), LEFT(p_actual, 255));
END$$

-- the value must be exactly the expected one
DROP PROCEDURE IF EXISTS t_eq$$
CREATE PROCEDURE t_eq(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                      IN p_actual TEXT, IN p_expected TEXT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual <=> p_expected, 'PASS', 'FAIL'),
                  IFNULL(p_expected, 'NULL'), IFNULL(p_actual, 'NULL'));
END$$

-- the value must be at least the expected minimum (the row counts of 3.1.1)
DROP PROCEDURE IF EXISTS t_min$$
CREATE PROCEDURE t_min(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual BIGINT, IN p_min BIGINT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual >= p_min, 'PASS', 'FAIL'),
                  CONCAT('>= ', p_min), CAST(p_actual AS CHAR));
END$$

-- the value must contain the expected text
DROP PROCEDURE IF EXISTS t_has$$
CREATE PROCEDURE t_has(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual TEXT, IN p_expected VARCHAR(255))
BEGIN
    CALL t_record(p_section, p_test,
                  IF(INSTR(IFNULL(p_actual, ''), p_expected) > 0, 'PASS', 'FAIL'),
                  CONCAT('contains "', p_expected, '"'), IFNULL(p_actual, 'NULL'));
END$$

-- THE REFUSED PATH: the statement must fail, with a message we expect.
-- The handler catches the SIGNAL raised by a trigger or a procedure, so the
-- suite can carry on and report it as a passing test.
DROP PROCEDURE IF EXISTS t_error$$
CREATE PROCEDURE t_error(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                         IN p_sql TEXT, IN p_expected VARCHAR(255))
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    IF v_msg = '' THEN
        CALL t_record(p_section, p_test, 'FAIL',
                      CONCAT('refused: "', p_expected, '"'), 'the statement was ACCEPTED');
    ELSE
        CALL t_record(p_section, p_test, IF(INSTR(v_msg, p_expected) > 0, 'PASS', 'FAIL'),
                      CONCAT('refused: "', p_expected, '"'), v_msg);
    END IF;
END$$

-- THE ACCEPTED PATH: the statement must go through without an error
DROP PROCEDURE IF EXISTS t_ok$$
CREATE PROCEDURE t_ok(IN p_section VARCHAR(60), IN p_test VARCHAR(200), IN p_sql TEXT)
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    CALL t_record(p_section, p_test, IF(v_msg = '', 'PASS', 'FAIL'), 'accepted',
                  IF(v_msg = '', 'accepted', v_msg));
END$$

DELIMITER ;


-- #####################################################################
--  Everything from here is undone by the ROLLBACK below
-- #####################################################################
START TRANSACTION;

-- =====================================================================
--  SECTION 9 - 3.1.3.3  Booking the accommodation of a whole trip
-- ---------------------------------------------------------------------
--  Procedure: sp_book_trip_accommodation(trip)
--  The "Auto-Book Accommodations" button of the Trips screen. For every
--  destination of the trip, in visit order, it books the best lodging
--  sp_search_accommodation offers, for the dates of that stay.
--  Rooms needed = CEIL(confirmed or paid reservations / 2) - double rooms.
--  Outcomes:
--    A. booked, one lodging per destination                     (tested)
--    B. run again -> the previous bookings are replaced, not added (tested)
--    C. refused: the trip does not exist                        (tested)
--    D. refused: nobody has confirmed or paid, so nothing to book (tested)
--    E. refused: one destination has no free room -> EVERY booking
--       of the trip is cancelled, not just that one              (tested)
--    F. a trip with no destinations books nothing and fails not  (tested)
--  Trip 1 visits Paris (1-5 June) and London (5-10 June).
-- =====================================================================

-- A. the normal case
CALL sp_book_trip_accommodation(1);
CALL t_eq('9. 3.1.3.3 auto-booking', 'A. one lodging is booked per destination of trip 1',
    (SELECT COUNT(*) FROM room_usage WHERE ru_trip_id = 1), '2');
CALL t_eq('9. 3.1.3.3 auto-booking', 'A. the Paris leg is 4 nights x 250 for one room',
    (SELECT ru_total_cost FROM room_usage ru JOIN lodging l ON l.lg_id = ru.ru_lodging_id
     WHERE ru.ru_trip_id = 1 AND l.lg_name = 'Le Grand Paris'), '1000.00');
CALL t_eq('9. 3.1.3.3 auto-booking', 'A. the London leg is 5 nights x 60 for one room',
    (SELECT ru_total_cost FROM room_usage ru JOIN lodging l ON l.lg_id = ru.ru_lodging_id
     WHERE ru.ru_trip_id = 1 AND l.lg_name = 'London Stay'), '300.00');
CALL t_eq('9. 3.1.3.3 auto-booking', 'A. the accommodation of the whole trip costs 1300',
    (SELECT SUM(ru_total_cost) FROM room_usage WHERE ru_trip_id = 1), '1300.00');
CALL t_eq('9. 3.1.3.3 auto-booking', 'A. the stays are booked for the dates of the trip',
    (SELECT CONCAT(MIN(ru_checkin), ' to ', MAX(ru_checkout)) FROM room_usage WHERE ru_trip_id = 1),
    '2026-06-01 to 2026-06-10');

-- B. booking again replaces, it does not add
CALL sp_book_trip_accommodation(1);
CALL t_eq('9. 3.1.3.3 auto-booking', 'B. running it again replaces the bookings (still 2, not 4)',
    (SELECT COUNT(*) FROM room_usage WHERE ru_trip_id = 1), '2');

-- rooms follow the number of passengers: trip 3 has 3 paid reservations
CALL sp_book_trip_accommodation(3);
CALL t_eq('9. 3.1.3.3 auto-booking', 'one room per two passengers: 3 passengers need 2 rooms',
    (SELECT DISTINCT ru_rooms_count FROM room_usage WHERE ru_trip_id = 3), '2');

-- C. and D. the refused paths
CALL t_error('9. 3.1.3.3 auto-booking', 'C. an unknown trip is refused',
    'CALL sp_book_trip_accommodation(9999)', 'trip does not exist');
UPDATE reservation SET res_status = 'PENDING' WHERE res_tr_id = 12;
CALL t_error('9. 3.1.3.3 auto-booking', 'D. a trip where nobody has confirmed or paid is refused',
    'CALL sp_book_trip_accommodation(12)', 'no confirmed or paid reservations');
UPDATE reservation SET res_status = 'CONFIRMED' WHERE res_tr_id = 12;

-- E. a leg that cannot be booked cancels the whole trip, not half of it
UPDATE lodging SET lg_total_rooms = 0 WHERE lg_id = 2;   -- London Stay has no rooms left
CALL t_error('9. 3.1.3.3 auto-booking', 'E. a destination without a free room is named in the error',
    'CALL sp_book_trip_accommodation(1)', 'no lodging in London with 1 free room(s)');
CALL t_eq('9. 3.1.3.3 auto-booking', 'E. and the Paris booking is cancelled as well - all or nothing',
    (SELECT COUNT(*) FROM room_usage WHERE ru_trip_id = 1), '0');
UPDATE lodging SET lg_total_rooms = 30 WHERE lg_id = 2;

-- F. a trip that visits nowhere yet
INSERT INTO trip (tr_departure, tr_return, tr_maxseats, tr_cost_adult, tr_cost_child,
                  tr_status, tr_min_participants, tr_br_code)
VALUES ('2027-06-01', '2027-06-05', 10, 100, 50, 'PLANNED', 2, 1);
SET @empty_trip = LAST_INSERT_ID();
INSERT INTO reservation (res_tr_id, res_seatnum, res_cust_id, res_status, res_total_cost)
VALUES (@empty_trip, 1, 1, 'CONFIRMED', 100);
CALL t_ok('9. 3.1.3.3 auto-booking', 'F. a trip without destinations is not an error',
    CONCAT('CALL sp_book_trip_accommodation(', @empty_trip, ')'));
CALL t_eq('9. 3.1.3.3 auto-booking', 'F. and nothing is booked for it',
    (SELECT COUNT(*) FROM room_usage WHERE ru_trip_id = @empty_trip), '0');
DELETE FROM reservation WHERE res_tr_id = @empty_trip;
DELETE FROM trip WHERE tr_id = @empty_trip;

DELETE FROM room_usage;


-- #####################################################################
--  Undo everything the checks did
-- #####################################################################
ROLLBACK;


-- #####################################################################
--  THE REPORT
-- #####################################################################

-- 1. every check, in order
SELECT id, section, test, status FROM test_results ORDER BY id;

-- 2. the failures on their own, with what was expected and what came back
SELECT id, section, test, expected, actual
FROM test_results WHERE status = 'FAIL' ORDER BY id;

-- 3. the summary
SELECT COUNT(*)             AS total,
       SUM(status = 'PASS') AS passed,
       SUM(status = 'FAIL') AS failed,
       IF(SUM(status = 'FAIL') = 0, 'ALL TESTS PASSED', 'THERE ARE FAILURES') AS result
FROM test_results;

-- 4. the proof that the database was left exactly as it was found
SELECT 'the tests changed nothing' AS note,
       (SELECT COUNT(*) FROM customer)    AS customers,
       (SELECT COUNT(*) FROM reservation) AS reservations,
       (SELECT COUNT(*) FROM room_usage)  AS room_usage_rows,
       (SELECT COUNT(*) FROM log_actions) AS log_rows,
       (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9) AS vehicle_9,
       (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101')                AS salary_AT101;


-- #####################################################################
--  Remove the harness again
-- #####################################################################
DROP PROCEDURE IF EXISTS t_record;
DROP PROCEDURE IF EXISTS t_eq;
DROP PROCEDURE IF EXISTS t_min;
DROP PROCEDURE IF EXISTS t_has;
DROP PROCEDURE IF EXISTS t_error;
DROP PROCEDURE IF EXISTS t_ok;
DROP TEMPORARY TABLE IF EXISTS test_results;
