-- #####################################################################
--  gui_salary_guard.sql
--  The salary guard
-- #####################################################################
--  GENERATED from queries/Tests.sql (section 14) by
--  tests/split_sql_tests.sh - edit Tests.sql and run the script again,
--  do not edit this file by hand.
--
--  It runs on its own: it installs the small test harness, runs the
--  checks of this one question inside a transaction, rolls everything
--  back and prints a PASS/FAIL report. It changes nothing.
--  (The client warns about a non-transactional table at the end: that
--  is the MEMORY table that carries the report through the rollback.)
--
--  Run it with
--    docker exec -i baseis-mariadb mariadb -uroot -pjohn2005 -t baseisproject < queries/tests/gui_salary_guard.sql
--  or open it in a SQL client and execute the whole file.
-- #####################################################################

-- #####################################################################
--  THE TEST HARNESS
--  Six helper procedures record one line per check instead of stopping at
--  the first failure, so one run reports everything at once.
--  They are dropped again at the end of the file.
-- #####################################################################

DROP TEMPORARY TABLE IF EXISTS test_results;
CREATE TEMPORARY TABLE test_results (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    section  VARCHAR(60),
    test     VARCHAR(200),
    status   VARCHAR(4),
    expected VARCHAR(255),
    actual   VARCHAR(255)
) ENGINE = MEMORY;   -- MEMORY is not transactional: the report survives the ROLLBACK

DELIMITER $$

-- write one line of the report
DROP PROCEDURE IF EXISTS t_record$$
CREATE PROCEDURE t_record(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                          IN p_status VARCHAR(4), IN p_expected VARCHAR(255), IN p_actual VARCHAR(255))
BEGIN
    INSERT INTO test_results (section, test, status, expected, actual)
    VALUES (p_section, p_test, p_status, LEFT(p_expected, 255), LEFT(p_actual, 255));
END$$

-- the value must be exactly the expected one
DROP PROCEDURE IF EXISTS t_eq$$
CREATE PROCEDURE t_eq(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                      IN p_actual TEXT, IN p_expected TEXT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual <=> p_expected, 'PASS', 'FAIL'),
                  IFNULL(p_expected, 'NULL'), IFNULL(p_actual, 'NULL'));
END$$

-- the value must be at least the expected minimum (the row counts of 3.1.1)
DROP PROCEDURE IF EXISTS t_min$$
CREATE PROCEDURE t_min(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual BIGINT, IN p_min BIGINT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual >= p_min, 'PASS', 'FAIL'),
                  CONCAT('>= ', p_min), CAST(p_actual AS CHAR));
END$$

-- the value must contain the expected text
DROP PROCEDURE IF EXISTS t_has$$
CREATE PROCEDURE t_has(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual TEXT, IN p_expected VARCHAR(255))
BEGIN
    CALL t_record(p_section, p_test,
                  IF(INSTR(IFNULL(p_actual, ''), p_expected) > 0, 'PASS', 'FAIL'),
                  CONCAT('contains "', p_expected, '"'), IFNULL(p_actual, 'NULL'));
END$$

-- THE REFUSED PATH: the statement must fail, with a message we expect.
-- The handler catches the SIGNAL raised by a trigger or a procedure, so the
-- suite can carry on and report it as a passing test.
DROP PROCEDURE IF EXISTS t_error$$
CREATE PROCEDURE t_error(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                         IN p_sql TEXT, IN p_expected VARCHAR(255))
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    IF v_msg = '' THEN
        CALL t_record(p_section, p_test, 'FAIL',
                      CONCAT('refused: "', p_expected, '"'), 'the statement was ACCEPTED');
    ELSE
        CALL t_record(p_section, p_test, IF(INSTR(v_msg, p_expected) > 0, 'PASS', 'FAIL'),
                      CONCAT('refused: "', p_expected, '"'), v_msg);
    END IF;
END$$

-- THE ACCEPTED PATH: the statement must go through without an error
DROP PROCEDURE IF EXISTS t_ok$$
CREATE PROCEDURE t_ok(IN p_section VARCHAR(60), IN p_test VARCHAR(200), IN p_sql TEXT)
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    CALL t_record(p_section, p_test, IF(v_msg = '', 'PASS', 'FAIL'), 'accepted',
                  IF(v_msg = '', 'accepted', v_msg));
END$$

DELIMITER ;


-- #####################################################################
--  Everything from here is undone by the ROLLBACK below
-- #####################################################################
START TRANSACTION;

-- =====================================================================
--  SECTION 14 - The salary guard
-- ---------------------------------------------------------------------
--  Trigger: trg_worker_salary_increase (BEFORE UPDATE ON worker)
--  Behind "Update Salary" on the Staff screen. A raise is only allowed
--  when the branch is profitable AND the raise is at most 2 %.
--  Outcomes - every branch of the trigger is exercised:
--    A. the salary goes DOWN            -> always allowed (no check at all)
--    B. the salary does not change      -> allowed
--    C. raise of 1 %, branch profitable -> ALLOWED
--    D. raise of exactly 2 %            -> ALLOWED (the limit itself)
--    E. raise above 2 %                 -> REFUSED
--    F. any raise, branch not profitable-> REFUSED
--
--  With the seeded salaries no branch is profitable (one round of
--  reservations against a month of salaries), so the salaries of branch 1
--  are lowered first - which is outcome A, and allowed.
-- =====================================================================

-- A. lowering is always allowed, no matter what the branch earns
CALL t_ok('14. salary guard', 'A. lowering a salary is always allowed',
    'UPDATE worker SET wrk_salary = 100 WHERE wrk_br_code = 1');
CALL t_eq('14. salary guard', 'A. the lower salary is stored',
    (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101'), '100.00');

-- B. an update that does not touch the salary is not a raise
CALL t_ok('14. salary guard', 'B. changing something else about the worker is allowed',
    "UPDATE worker SET wrk_email = 'changed@ag.gr' WHERE wrk_AT = 'AT101'");

-- branch 1 now earns more than it pays
CALL sp_branch_financials(1, @revenue, @expenses, @ratio);
CALL t_eq('14. salary guard', 'branch 1 is profitable now, so a raise may be considered',
    IF(@ratio > 0, 'profitable', CONCAT('ratio ', @ratio)), 'profitable');

-- C. a small raise in a profitable branch
CALL t_ok('14. salary guard', 'C. a raise of 1 % in a profitable branch is ALLOWED',
    "UPDATE worker SET wrk_salary = 101 WHERE wrk_AT = 'AT101'");
CALL t_eq('14. salary guard', 'C. the new salary is stored',
    (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101'), '101.00');

-- D. exactly on the limit
UPDATE worker SET wrk_salary = 100 WHERE wrk_AT = 'AT101';
CALL t_ok('14. salary guard', 'D. a raise of exactly 2 % is ALLOWED (the limit itself)',
    "UPDATE worker SET wrk_salary = 102 WHERE wrk_AT = 'AT101'");
CALL t_eq('14. salary guard', 'D. the salary on the limit is stored',
    (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101'), '102.00');

-- E. over the limit
CALL t_error('14. salary guard', 'E. a raise above 2 % is REFUSED',
    "UPDATE worker SET wrk_salary = 110 WHERE wrk_AT = 'AT101'", 'exceeds 2% limit');
CALL t_eq('14. salary guard', 'E. the refused raise did not change the salary',
    (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101'), '102.00');

-- F. the branch stops making money: no raise at all, however small
UPDATE reservation SET res_total_cost = 0;
CALL t_error('14. salary guard', 'F. even a 1 % raise is REFUSED when the branch makes no profit',
    "UPDATE worker SET wrk_salary = 103 WHERE wrk_AT = 'AT101'", 'branch is not profitable');
CALL t_ok('14. salary guard', 'F. but lowering a salary is still allowed',
    "UPDATE worker SET wrk_salary = 50 WHERE wrk_AT = 'AT101'");


-- #####################################################################
--  Undo everything the checks did
-- #####################################################################
ROLLBACK;


-- #####################################################################
--  THE REPORT
-- #####################################################################

-- 1. every check, in order
SELECT id, section, test, status FROM test_results ORDER BY id;

-- 2. the failures on their own, with what was expected and what came back
SELECT id, section, test, expected, actual
FROM test_results WHERE status = 'FAIL' ORDER BY id;

-- 3. the summary
SELECT COUNT(*)             AS total,
       SUM(status = 'PASS') AS passed,
       SUM(status = 'FAIL') AS failed,
       IF(SUM(status = 'FAIL') = 0, 'ALL TESTS PASSED', 'THERE ARE FAILURES') AS result
FROM test_results;

-- 4. the proof that the database was left exactly as it was found
SELECT 'the tests changed nothing' AS note,
       (SELECT COUNT(*) FROM customer)    AS customers,
       (SELECT COUNT(*) FROM reservation) AS reservations,
       (SELECT COUNT(*) FROM room_usage)  AS room_usage_rows,
       (SELECT COUNT(*) FROM log_actions) AS log_rows,
       (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9) AS vehicle_9,
       (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101')                AS salary_AT101;


-- #####################################################################
--  Remove the harness again
-- #####################################################################
DROP PROCEDURE IF EXISTS t_record;
DROP PROCEDURE IF EXISTS t_eq;
DROP PROCEDURE IF EXISTS t_min;
DROP PROCEDURE IF EXISTS t_has;
DROP PROCEDURE IF EXISTS t_error;
DROP PROCEDURE IF EXISTS t_ok;
DROP TEMPORARY TABLE IF EXISTS test_results;
