-- #####################################################################
--  rules_section2_check_constraints.sql
--  section 2 rules the database ENFORCES (CHECK constraints)
-- #####################################################################
--  GENERATED from queries/Tests.sql (section 4) by
--  tests/split_sql_tests.sh - edit Tests.sql and run the script again,
--  do not edit this file by hand.
--
--  It runs on its own: it installs the small test harness, runs the
--  checks of this one question inside a transaction, rolls everything
--  back and prints a PASS/FAIL report. It changes nothing.
--  (The client warns about a non-transactional table at the end: that
--  is the MEMORY table that carries the report through the rollback.)
--
--  Run it with
--    docker exec -i baseis-mariadb mariadb -uroot -pjohn2005 -t baseisproject < queries/tests/rules_section2_check_constraints.sql
--  or open it in a SQL client and execute the whole file.
-- #####################################################################

-- #####################################################################
--  THE TEST HARNESS
--  Six helper procedures record one line per check instead of stopping at
--  the first failure, so one run reports everything at once.
--  They are dropped again at the end of the file.
-- #####################################################################

DROP TEMPORARY TABLE IF EXISTS test_results;
CREATE TEMPORARY TABLE test_results (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    section  VARCHAR(60),
    test     VARCHAR(200),
    status   VARCHAR(4),
    expected VARCHAR(255),
    actual   VARCHAR(255)
) ENGINE = MEMORY;   -- MEMORY is not transactional: the report survives the ROLLBACK

DELIMITER $$

-- write one line of the report
DROP PROCEDURE IF EXISTS t_record$$
CREATE PROCEDURE t_record(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                          IN p_status VARCHAR(4), IN p_expected VARCHAR(255), IN p_actual VARCHAR(255))
BEGIN
    INSERT INTO test_results (section, test, status, expected, actual)
    VALUES (p_section, p_test, p_status, LEFT(p_expected, 255), LEFT(p_actual, 255));
END$$

-- the value must be exactly the expected one
DROP PROCEDURE IF EXISTS t_eq$$
CREATE PROCEDURE t_eq(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                      IN p_actual TEXT, IN p_expected TEXT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual <=> p_expected, 'PASS', 'FAIL'),
                  IFNULL(p_expected, 'NULL'), IFNULL(p_actual, 'NULL'));
END$$

-- the value must be at least the expected minimum (the row counts of 3.1.1)
DROP PROCEDURE IF EXISTS t_min$$
CREATE PROCEDURE t_min(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual BIGINT, IN p_min BIGINT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual >= p_min, 'PASS', 'FAIL'),
                  CONCAT('>= ', p_min), CAST(p_actual AS CHAR));
END$$

-- the value must contain the expected text
DROP PROCEDURE IF EXISTS t_has$$
CREATE PROCEDURE t_has(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual TEXT, IN p_expected VARCHAR(255))
BEGIN
    CALL t_record(p_section, p_test,
                  IF(INSTR(IFNULL(p_actual, ''), p_expected) > 0, 'PASS', 'FAIL'),
                  CONCAT('contains "', p_expected, '"'), IFNULL(p_actual, 'NULL'));
END$$

-- THE REFUSED PATH: the statement must fail, with a message we expect.
-- The handler catches the SIGNAL raised by a trigger or a procedure, so the
-- suite can carry on and report it as a passing test.
DROP PROCEDURE IF EXISTS t_error$$
CREATE PROCEDURE t_error(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                         IN p_sql TEXT, IN p_expected VARCHAR(255))
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    IF v_msg = '' THEN
        CALL t_record(p_section, p_test, 'FAIL',
                      CONCAT('refused: "', p_expected, '"'), 'the statement was ACCEPTED');
    ELSE
        CALL t_record(p_section, p_test, IF(INSTR(v_msg, p_expected) > 0, 'PASS', 'FAIL'),
                      CONCAT('refused: "', p_expected, '"'), v_msg);
    END IF;
END$$

-- THE ACCEPTED PATH: the statement must go through without an error
DROP PROCEDURE IF EXISTS t_ok$$
CREATE PROCEDURE t_ok(IN p_section VARCHAR(60), IN p_test VARCHAR(200), IN p_sql TEXT)
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    CALL t_record(p_section, p_test, IF(v_msg = '', 'PASS', 'FAIL'), 'accepted',
                  IF(v_msg = '', 'accepted', v_msg));
END$$

DELIMITER ;


-- #####################################################################
--  Everything from here is undone by the ROLLBACK below
-- #####################################################################
START TRANSACTION;

-- =====================================================================
--  SECTION 4 - section 2 rules the database ENFORCES (CHECK constraints)
-- ---------------------------------------------------------------------
--  Section 3 showed the data obeys the rules. This section shows the
--  database would not let you break them, and that correct data still
--  goes in - a constraint that refuses everything is not useful either.
--
--  chk_vehicle_type_seats : Bus > 20, Mini-Bus 10-20, Van 6-9, Car 1-5
--  chk_lodging_stars_type : only a Hotel or a Resort may have stars
--  lodging_chk_1          : stars are 1 to 5
--  lodging_chk_2          : the rating is 0.00 to 5.00
-- =====================================================================

-- --- the accepted path: valid rows of every vehicle type go in ---------
CALL t_ok('4. CHECK constraints', 'a Car with 5 seats is accepted',
    "INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
     VALUES (1, 'CHK-0001', 'M', 'B', 'Car', 5)");
CALL t_ok('4. CHECK constraints', 'a Van with 9 seats is accepted',
    "INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
     VALUES (1, 'CHK-0002', 'M', 'B', 'Van', 9)");
CALL t_ok('4. CHECK constraints', 'a Mini-Bus with 20 seats is accepted',
    "INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
     VALUES (1, 'CHK-0003', 'M', 'B', 'Mini-Bus', 20)");
CALL t_ok('4. CHECK constraints', 'a Bus with 21 seats is accepted',
    "INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
     VALUES (1, 'CHK-0004', 'M', 'B', 'Bus', 21)");

-- --- the refused path: one for every branch of the constraint ----------
CALL t_error('4. CHECK constraints', 'a Car with 30 seats is refused',
    "INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
     VALUES (1, 'CHK-0005', 'M', 'B', 'Car', 30)", 'chk_vehicle_type_seats');
CALL t_error('4. CHECK constraints', 'a Bus with 8 seats is refused',
    "INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
     VALUES (1, 'CHK-0006', 'M', 'B', 'Bus', 8)", 'chk_vehicle_type_seats');
CALL t_error('4. CHECK constraints', 'a Mini-Bus with 25 seats is refused (that is a Bus)',
    "INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
     VALUES (1, 'CHK-0007', 'M', 'B', 'Mini-Bus', 25)", 'chk_vehicle_type_seats');
CALL t_error('4. CHECK constraints', 'a Van with 12 seats is refused (that is a Mini-Bus)',
    "INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
     VALUES (1, 'CHK-0008', 'M', 'B', 'Van', 12)", 'chk_vehicle_type_seats');
-- the same rule on UPDATE, not only on INSERT
CALL t_error('4. CHECK constraints', 'turning a Bus into a Car is refused as well',
    "UPDATE vehicle SET v_type = 'Car' WHERE v_id = 1", 'chk_vehicle_type_seats');

-- --- lodging: stars belong to hotels and resorts only ------------------
CALL t_ok('4. CHECK constraints', 'a hotel WITH stars is accepted',
    "INSERT INTO lodging (lg_dst_id, lg_name, lg_type, lg_stars, lg_address, lg_city, lg_total_rooms, lg_cost_per_night)
     VALUES (2, 'Chk Hotel', 'Hotel', 4, 'a', 'London', 5, 10)");
CALL t_ok('4. CHECK constraints', 'a hotel that has not been rated yet is accepted (stars may be unknown)',
    "INSERT INTO lodging (lg_dst_id, lg_name, lg_type, lg_address, lg_city, lg_total_rooms, lg_cost_per_night)
     VALUES (2, 'Chk Unrated', 'Hotel', 'a', 'London', 5, 10)");
CALL t_ok('4. CHECK constraints', 'a hostel WITHOUT stars is accepted',
    "INSERT INTO lodging (lg_dst_id, lg_name, lg_type, lg_address, lg_city, lg_total_rooms, lg_cost_per_night)
     VALUES (2, 'Chk Hostel', 'Hostel', 'a', 'London', 5, 10)");
CALL t_error('4. CHECK constraints', 'a hostel WITH stars is refused',
    "INSERT INTO lodging (lg_dst_id, lg_name, lg_type, lg_stars, lg_address, lg_city, lg_total_rooms, lg_cost_per_night)
     VALUES (2, 'Chk Bad Hostel', 'Hostel', 3, 'a', 'London', 5, 10)", 'chk_lodging_stars_type');
CALL t_error('4. CHECK constraints', 'giving stars to an apartment by UPDATE is refused',
    "UPDATE lodging SET lg_stars = 4 WHERE lg_name = 'Roma Bella'", 'chk_lodging_stars_type');
CALL t_error('4. CHECK constraints', 'a 6-star hotel is refused (stars are 1 to 5)',
    "INSERT INTO lodging (lg_dst_id, lg_name, lg_type, lg_stars, lg_address, lg_city, lg_total_rooms, lg_cost_per_night)
     VALUES (2, 'Chk Six Star', 'Hotel', 6, 'a', 'London', 5, 10)", 'lodging_chk_1');
CALL t_error('4. CHECK constraints', 'a rating of 9 is refused (the rating is 0 to 5)',
    "INSERT INTO lodging (lg_dst_id, lg_name, lg_type, lg_rating, lg_address, lg_city, lg_total_rooms, lg_cost_per_night)
     VALUES (2, 'Chk Rating', 'Hostel', 9.0, 'a', 'London', 5, 10)", 'lodging_chk_2');

-- --- referential integrity --------------------------------------------
CALL t_error('4. CHECK constraints', 'a vehicle of a branch that does not exist is refused',
    "INSERT INTO vehicle (v_br_code, v_license_plate, v_model, v_brand, v_type, v_seats)
     VALUES (999, 'CHK-0009', 'M', 'B', 'Car', 4)", 'foreign key constraint fails');
CALL t_error('4. CHECK constraints', 'the same seat cannot be booked twice on one trip',
    "INSERT INTO reservation (res_tr_id, res_seatnum, res_cust_id, res_status)
     VALUES (1, 1, 5, 'PENDING')", 'Duplicate entry');

DELETE FROM vehicle WHERE v_license_plate LIKE 'CHK-%';
DELETE FROM lodging WHERE lg_name LIKE 'Chk %';


-- #####################################################################
--  Undo everything the checks did
-- #####################################################################
ROLLBACK;


-- #####################################################################
--  THE REPORT
-- #####################################################################

-- 1. every check, in order
SELECT id, section, test, status FROM test_results ORDER BY id;

-- 2. the failures on their own, with what was expected and what came back
SELECT id, section, test, expected, actual
FROM test_results WHERE status = 'FAIL' ORDER BY id;

-- 3. the summary
SELECT COUNT(*)             AS total,
       SUM(status = 'PASS') AS passed,
       SUM(status = 'FAIL') AS failed,
       IF(SUM(status = 'FAIL') = 0, 'ALL TESTS PASSED', 'THERE ARE FAILURES') AS result
FROM test_results;

-- 4. the proof that the database was left exactly as it was found
SELECT 'the tests changed nothing' AS note,
       (SELECT COUNT(*) FROM customer)    AS customers,
       (SELECT COUNT(*) FROM reservation) AS reservations,
       (SELECT COUNT(*) FROM room_usage)  AS room_usage_rows,
       (SELECT COUNT(*) FROM log_actions) AS log_rows,
       (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9) AS vehicle_9,
       (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101')                AS salary_AT101;


-- #####################################################################
--  Remove the harness again
-- #####################################################################
DROP PROCEDURE IF EXISTS t_record;
DROP PROCEDURE IF EXISTS t_eq;
DROP PROCEDURE IF EXISTS t_min;
DROP PROCEDURE IF EXISTS t_has;
DROP PROCEDURE IF EXISTS t_error;
DROP PROCEDURE IF EXISTS t_ok;
DROP TEMPORARY TABLE IF EXISTS test_results;
