-- #####################################################################
--  rules_section2_data.sql
--  The business rules of section 2 of the description
-- #####################################################################
--  GENERATED from queries/Tests.sql (section 3) by
--  tests/split_sql_tests.sh - edit Tests.sql and run the script again,
--  do not edit this file by hand.
--
--  It runs on its own: it installs the small test harness, runs the
--  checks of this one question inside a transaction, rolls everything
--  back and prints a PASS/FAIL report. It changes nothing.
--  (The client warns about a non-transactional table at the end: that
--  is the MEMORY table that carries the report through the rollback.)
--
--  Run it with
--    docker exec -i baseis-mariadb mariadb -uroot -pjohn2005 -t baseisproject < queries/tests/rules_section2_data.sql
--  or open it in a SQL client and execute the whole file.
-- #####################################################################

-- #####################################################################
--  THE TEST HARNESS
--  Six helper procedures record one line per check instead of stopping at
--  the first failure, so one run reports everything at once.
--  They are dropped again at the end of the file.
-- #####################################################################

DROP TEMPORARY TABLE IF EXISTS test_results;
CREATE TEMPORARY TABLE test_results (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    section  VARCHAR(60),
    test     VARCHAR(200),
    status   VARCHAR(4),
    expected VARCHAR(255),
    actual   VARCHAR(255)
) ENGINE = MEMORY;   -- MEMORY is not transactional: the report survives the ROLLBACK

DELIMITER $$

-- write one line of the report
DROP PROCEDURE IF EXISTS t_record$$
CREATE PROCEDURE t_record(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                          IN p_status VARCHAR(4), IN p_expected VARCHAR(255), IN p_actual VARCHAR(255))
BEGIN
    INSERT INTO test_results (section, test, status, expected, actual)
    VALUES (p_section, p_test, p_status, LEFT(p_expected, 255), LEFT(p_actual, 255));
END$$

-- the value must be exactly the expected one
DROP PROCEDURE IF EXISTS t_eq$$
CREATE PROCEDURE t_eq(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                      IN p_actual TEXT, IN p_expected TEXT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual <=> p_expected, 'PASS', 'FAIL'),
                  IFNULL(p_expected, 'NULL'), IFNULL(p_actual, 'NULL'));
END$$

-- the value must be at least the expected minimum (the row counts of 3.1.1)
DROP PROCEDURE IF EXISTS t_min$$
CREATE PROCEDURE t_min(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual BIGINT, IN p_min BIGINT)
BEGIN
    CALL t_record(p_section, p_test,
                  IF(p_actual >= p_min, 'PASS', 'FAIL'),
                  CONCAT('>= ', p_min), CAST(p_actual AS CHAR));
END$$

-- the value must contain the expected text
DROP PROCEDURE IF EXISTS t_has$$
CREATE PROCEDURE t_has(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                       IN p_actual TEXT, IN p_expected VARCHAR(255))
BEGIN
    CALL t_record(p_section, p_test,
                  IF(INSTR(IFNULL(p_actual, ''), p_expected) > 0, 'PASS', 'FAIL'),
                  CONCAT('contains "', p_expected, '"'), IFNULL(p_actual, 'NULL'));
END$$

-- THE REFUSED PATH: the statement must fail, with a message we expect.
-- The handler catches the SIGNAL raised by a trigger or a procedure, so the
-- suite can carry on and report it as a passing test.
DROP PROCEDURE IF EXISTS t_error$$
CREATE PROCEDURE t_error(IN p_section VARCHAR(60), IN p_test VARCHAR(200),
                         IN p_sql TEXT, IN p_expected VARCHAR(255))
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    IF v_msg = '' THEN
        CALL t_record(p_section, p_test, 'FAIL',
                      CONCAT('refused: "', p_expected, '"'), 'the statement was ACCEPTED');
    ELSE
        CALL t_record(p_section, p_test, IF(INSTR(v_msg, p_expected) > 0, 'PASS', 'FAIL'),
                      CONCAT('refused: "', p_expected, '"'), v_msg);
    END IF;
END$$

-- THE ACCEPTED PATH: the statement must go through without an error
DROP PROCEDURE IF EXISTS t_ok$$
CREATE PROCEDURE t_ok(IN p_section VARCHAR(60), IN p_test VARCHAR(200), IN p_sql TEXT)
BEGIN
    DECLARE v_msg TEXT DEFAULT '';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        GET DIAGNOSTICS CONDITION 1 v_msg = MESSAGE_TEXT;

    SET @t_sql = p_sql;
    PREPARE t_stmt FROM @t_sql;
    EXECUTE t_stmt;
    DEALLOCATE PREPARE t_stmt;

    CALL t_record(p_section, p_test, IF(v_msg = '', 'PASS', 'FAIL'), 'accepted',
                  IF(v_msg = '', 'accepted', v_msg));
END$$

DELIMITER ;


-- #####################################################################
--  Everything from here is undone by the ROLLBACK below
-- #####################################################################
START TRANSACTION;

-- =====================================================================
--  SECTION 3 - The business rules of section 2 of the description
-- ---------------------------------------------------------------------
--  These are the rules of the entity/relationship model. Here they are
--  checked against the data itself: the query counts the rows that break
--  the rule, so the expected answer is always 0.
-- =====================================================================
CALL t_eq('3. section 2 rules', 'a worker is a driver, a guide or an admin - exactly one',
    (SELECT COUNT(*) FROM worker w
     WHERE (SELECT COUNT(*) FROM driver WHERE drv_AT = w.wrk_AT)
         + (SELECT COUNT(*) FROM guide  WHERE gui_AT = w.wrk_AT)
         + (SELECT COUNT(*) FROM admin  WHERE adm_AT = w.wrk_AT) <> 1), '0');
CALL t_eq('3. section 2 rules', 'every branch has a phone and is managed by an admin',
    (SELECT COUNT(*) FROM branch b LEFT JOIN admin a ON a.adm_AT = b.br_manager_AT
     WHERE a.adm_AT IS NULL OR NOT EXISTS (SELECT 1 FROM phones p WHERE p.ph_br_code = b.br_code)), '0');
CALL t_eq('3. section 2 rules', 'every trip has at least one event',
    (SELECT COUNT(*) FROM trip t WHERE NOT EXISTS (SELECT 1 FROM event e WHERE e.ev_tr_id = t.tr_id)), '0');
CALL t_eq('3. section 2 rules', 'every trip states its minimum number of participants',
    (SELECT COUNT(*) FROM trip WHERE tr_min_participants IS NULL OR tr_min_participants < 1), '0');
CALL t_eq('3. section 2 rules', 'every guide speaks at least one language',
    (SELECT COUNT(*) FROM guide g WHERE NOT EXISTS (SELECT 1 FROM languages l WHERE l.lng_gui_AT = g.gui_AT)), '0');
CALL t_eq('3. section 2 rules', 'a driver only drives trips of their route (local/abroad)',
    (SELECT COUNT(*) FROM trip t
       JOIN driver d      ON d.drv_AT = t.tr_drv_AT
       JOIN travel_to x   ON x.to_tr_id = t.tr_id
       JOIN destination s ON s.dst_id = x.to_dst_id
     WHERE s.dst_rtype <> d.drv_route), '0');
CALL t_eq('3. section 2 rules', 'a driver of a vehicle with more than 9 seats holds licence C or D',
    (SELECT COUNT(*) FROM trip t
       JOIN vehicle v ON v.v_id = t.tr_vehicle_id
       JOIN driver d  ON d.drv_AT = t.tr_drv_AT
     WHERE v.v_seats > 9 AND d.drv_license NOT IN ('C', 'D')), '0');
CALL t_eq('3. section 2 rules', 'the number of seats matches the type of the vehicle',
    (SELECT COUNT(*) FROM vehicle
     WHERE NOT ((v_type = 'Bus'      AND v_seats > 20)
             OR (v_type = 'Mini-Bus' AND v_seats BETWEEN 10 AND 20)
             OR (v_type = 'Van'      AND v_seats BETWEEN 6 AND 9)
             OR (v_type = 'Car'      AND v_seats <= 5))), '0');
CALL t_eq('3. section 2 rules', 'only hotels and resorts carry stars',
    (SELECT COUNT(*) FROM lodging WHERE (lg_type IN ('Hotel', 'Resort')) <> (lg_stars IS NOT NULL)), '0');
CALL t_eq('3. section 2 rules', 'every lodging has a full address with a postal code',
    (SELECT COUNT(*) FROM lodging WHERE lg_postal_code IS NULL OR lg_address = '' OR lg_city = ''), '0');
CALL t_eq('3. section 2 rules', 'a city can belong to a country: Paris -> France',
    (SELECT p.dst_name FROM destination c JOIN destination p ON p.dst_id = c.dst_location
     WHERE c.dst_name = 'Paris'), 'France');
CALL t_eq('3. section 2 rules', 'no stay is shorter than one night',
    (SELECT COUNT(*) FROM travel_to WHERE DATEDIFF(to_departure, to_arrival) < 1), '0');
CALL t_eq('3. section 2 rules', 'every stay lies inside the dates of its trip',
    (SELECT COUNT(*) FROM travel_to tt JOIN trip t ON t.tr_id = tt.to_tr_id
     WHERE DATE(tt.to_arrival) < DATE(t.tr_departure)
        OR DATE(tt.to_departure) > DATE(t.tr_return)), '0');
CALL t_eq('3. section 2 rules', 'every reservation has a price',
    (SELECT COUNT(*) FROM reservation WHERE res_total_cost IS NULL OR res_total_cost = 0), '0');
CALL t_eq('3. section 2 rules', 'every logged action belongs to a registered DBA',
    (SELECT COUNT(*) FROM log_actions l LEFT JOIN dba_users d ON d.dba_username = l.log_dba_username
     WHERE d.dba_username IS NULL), '0');


-- #####################################################################
--  Undo everything the checks did
-- #####################################################################
ROLLBACK;


-- #####################################################################
--  THE REPORT
-- #####################################################################

-- 1. every check, in order
SELECT id, section, test, status FROM test_results ORDER BY id;

-- 2. the failures on their own, with what was expected and what came back
SELECT id, section, test, expected, actual
FROM test_results WHERE status = 'FAIL' ORDER BY id;

-- 3. the summary
SELECT COUNT(*)             AS total,
       SUM(status = 'PASS') AS passed,
       SUM(status = 'FAIL') AS failed,
       IF(SUM(status = 'FAIL') = 0, 'ALL TESTS PASSED', 'THERE ARE FAILURES') AS result
FROM test_results;

-- 4. the proof that the database was left exactly as it was found
SELECT 'the tests changed nothing' AS note,
       (SELECT COUNT(*) FROM customer)    AS customers,
       (SELECT COUNT(*) FROM reservation) AS reservations,
       (SELECT COUNT(*) FROM room_usage)  AS room_usage_rows,
       (SELECT COUNT(*) FROM log_actions) AS log_rows,
       (SELECT CONCAT(v_status, '/', v_mileage) FROM vehicle WHERE v_id = 9) AS vehicle_9,
       (SELECT wrk_salary FROM worker WHERE wrk_AT = 'AT101')                AS salary_AT101;


-- #####################################################################
--  Remove the harness again
-- #####################################################################
DROP PROCEDURE IF EXISTS t_record;
DROP PROCEDURE IF EXISTS t_eq;
DROP PROCEDURE IF EXISTS t_min;
DROP PROCEDURE IF EXISTS t_has;
DROP PROCEDURE IF EXISTS t_error;
DROP PROCEDURE IF EXISTS t_ok;
DROP TEMPORARY TABLE IF EXISTS test_results;
